#!/usr/bin/env bash

set -e

# The source repository
SRC_REPO=${SRC_REPO:-airbytehq/airbyte-platform}
# The source branch to be mirrored
SRC_BRANCH=${SRC_BRANCH}
# The source PR number
SRC_PR_NUM=${SRC_PR_NUM}
# The destination repository
DST_REPO=${DST_REPO:-airbytehq/airbyte-platform-internal}
# The destination branch
DST_BRANCH="${SRC_REPO}/${SRC_BRANCH}"
# The destination path
DST_PATH=${DST_PATH:-oss}


# Checkout destination
mkdir workspace
cd workspace
git clone https://x-access-token:${AUTH_TOKEN}@github.com/${DST_REPO}.git
cd ${DST_REPO##*/}

# Copy the branch from `airbytehq/airbyte`
echo gitx-copy branch https://x-access-token:${AUTH_TOKEN}@github.com/${SRC_REPO}.git $DST_PATH --src-ref=$SRC_BRANCH --push
echo gitx-copy pr https://x-access-token:${AUTH_TOKEN}@github.com/${SRC_REPO}.git  https://x-access-token:${AUTH_TOKEN}@github.com/${DST_REPO}.git $SRC_PR_NUM --base-branch=master --branch=${DST_BRANCH} --token=$AUTH_TOKEN
