apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-workload-api-server-svc
  {{- with .Values.workloadApiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workloadApiServer.service.type }}
  ports:
    - port: {{ .Values.workloadApiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.workloadApiServer.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.workloadApiServer.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
