# union of frontend, api, server, scheduler, protocol, worker, kubernetes
area/platform:
  - airbyte-api/*
  - airbyte-api/**/*
  - airbyte-persistence/*
  - airbyte-persistence/**/*
  - airbyte-server/*
  - airbyte-server/**/*
  - airbyte-workers/*
  - airbyte-workers/**/*
  - kube/*
  - kube/**/*
  - charts/*
  - charts/**/*

area/frontend:
  - airbyte-webapp/*
  - airbyte-webapp/**/*

area/api:
  - airbyte-api/*
  - airbyte-api/**/*

area/server:
  - airbyte-server/*
  - airbyte-server/**/*

area/worker:
  - airbyte-workers/*
  - airbyte-workers/**/*

kubernetes:
  - kube/*
  - kube/**/*
  - charts/*
  - charts/**/*

area/migration:
  - airbyte-db/*
