# Adds settings for allowing datadog metrics to be published from a local environment.
# This exists _only_ for testing datadog integrations!
#
# Usage:
# 1. create an API Key in datadog
# 2. wget -O dd-java-agent.jar 'https://dtdg.co/latest-java-tracer'.  NOTE: be sure this is downloaded to the directory you are running docker-compose from.  Probably /oss.  Docker won't warn you if the file is missing.
# 3. DD_API_KEY=[datadog api key] VERSION=dev docker-compose -f docker-compose.yaml -f docker-compose.datadog.yaml up -d
version: "3.8"

x-datadog-volumes: &datadogged-volumes
  volumes:
    - type: bind
      source: ./dd-java-agent.jar
      target: /dd-java-agent.jar

x-datadog-environment: &datadogged-environment
  METRIC_CLIENT: ${METRIC_CLIENT:-datadog}
  PUBLISH_METRICS: "true"
  DD_AGENT_HOST: airbyte-datadog
  DD_DOGSTATSD_PORT: ${DD_DOGSTATSD_PORT:-8125}
  DD_TRACE_AGENT_URL: http://airbyte-datadog
  JAVA_OPTS: -javaagent:/dd-java-agent.jar

services:
  db:
    ports:
      - 8011:5432
    networks:
      - airbyte_internal
      - airbyte_public
  datadog:
    image: datadog/agent:7-rc
    container_name: airbyte-datadog
    environment:
      - DD_API_KEY
      - DD_ENV=${DD_ENV:-local}
      - DD_SITE=datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - MICROMETER_METRICS_ENABLED=true
      - MICROMETER_METRICS_STATSD_FLAVOR=datadog
      - STATSD_HOST=airbyte-datadog
      - STATSD_PORT=8125
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
      - airbyte_internal
  init:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-init
  bootloader:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-bootloader
  worker:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-worker
      CONNECTOR_DATADOG_SUPPORT_NAMES: postgres-source
  server:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-server
  airbyte-api-server:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-api-server
  airbyte-connector-builder-server:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-connector-builder-server
  airbyte-cron:
    <<: *datadogged-volumes
    environment:
      <<: *datadogged-environment
      DD_SERVICE: airbyte-cron
