# Adds ports to the db and access to the temporal UI for debugging purposes.
# Expected to be used like this:
# VERSION=dev docker compose -f docker-compose.yaml -f docker-compose.debug.yaml up
version: "3.8"
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  airbyte-temporal:
    ports:
      - 7233:7233
  airbyte-temporal-ui:
    image: temporalio/ui:2.20.0
    logging: *default-logging
    container_name: airbyte-temporal-ui
    restart: unless-stopped
    environment:
      - TEMPORAL_ADDRESS=airbyte-temporal:7233
      - TEMPORAL_CORS_ORIGINS=true
    ports:
      - 8012:8080
    networks:
      - airbyte_internal
      - airbyte_public
  server:
    # Acceptance tests make more intensive use of the service than a typical local deployment, and there is only a
    # single server container in Docker, so we allow more threads to avoid getting overloaded.
    environment:
      - IO_TASK_EXECUTOR_THREADS=25
      - CONFIG_DB_MAX_POOL_SIZE=25
      - HEALTH_TASK_EXECUTOR_THREADS=25
      - SCHEDULER_TASK_EXECUTOR_THREADS=50
  # Acceptance tests do not need the webapp. Ideally we would not build the webapp
  # and deploy the webapp to save time (~ 5 mins) on CI. However, the proxy currently
  # written requires the webapp to run. So we pin the webapp to a specific commit.
  # This is not expected to change frequently - or at all.
  webapp:
    image: "airbyte/webapp:dev-521ad4842c"
configs:
  flags:
    file: ./tools/bin/acceptance-test-flags.yml
