#! /bin/sh

# Script that calculates the hash of all git tracked files as well as the files generated by orval

GENERATED_CLIENT_HASHES="$(cat .gitignore | grep '/src/core/request' | xargs -I %% sha1sum .%%)"
if [ -z "${GENERATED_CLIENT_HASHES}" ]; then
  # Fail if we can't find any file, so we don't accidentally forget to adjust the above path in case
  # we ever move the auto generated files to a different folder
  echo "Could not find any orval generated file to calculated hash."
  exit 25
fi

# Hash of all files tracked by git
SOURCE_HASHES="$(git ls-files | xargs sha1sum)"

# Build a single hash over all the hashes of all files and export it for usage in other programs
export SOURCE_HASH="$(echo "${GENERATED_CLIENT_HASHES}\n${SOURCE_HASHES}" | sha1sum | sed 's/  -//')"
