{{- if .Values.temporal.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-temporal
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.temporal.service.type }}
  ports:
  - port: {{ .Values.temporal.service.port }}
    protocol: TCP
    targetPort: 7233
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.temporal.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.temporal.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
{{- end }}
