{{- if (.Values.featureflagServer.enabled) }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "airbyte.namespace" . }}
  name: {{.Release.Name }}-featureflag-server-svc
  {{- with .Values.featureflagServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.featureflagServer.service.type }}
  {{- with .Values.featureflagServer.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- if and .Values.featureflagServer.service.externalTrafficPolicy (or (eq .Values.featureflagServer.service.type "NodePort") (eq .Values.featureflagServer.service.type "LoadBalancer")) }}
  externalTrafficPolicy: {{ .Values.featureflagServer.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.featureflagServer.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.featureflagServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.featureflagServer.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.featureflagServer.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.featureflagServer.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
{{- end }}
