{{- if and (.Values.featureflagServer.enabled) (eq .Values.global.edition "community") }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-featureflag-server-svc
  {{- with .Values.featureflagServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.featureflagServer.service.type }}
  ports:
    - port: {{ .Values.featureflagServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.featureflagServer.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.featureflagServer.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
{{- end }}
