##  global.serviceAccountName Name of service account to be associated with service
global:
  serviceAccountName: &service-account-name "airbyte-admin"
  # Docker image config that will apply to all images.
  image:
    # Docker registry to pull platform images from, e.g. http://my-registry:8000/
    registry: ""
    # Image tag to use for airbyte images. 
    # Does not include non-airbyte images such as temporal, minio, etc.
    tag: ""

enabled: true
##  podSweeper.image.repository The image repository to use for the pod sweeper
##  podSweeper.image.pullPolicy The pull policy for the pod sweeper image
##  podSweeper.image.tag The pod sweeper image tag to use
image:
  repository: airbyte/pod-sweeper
  pullPolicy: IfNotPresent

##  podSweeper.podAnnotations [object] Add extra annotations to the podSweeper pod
##
podAnnotations: {}

##  podSweeper.podLabels [object] Add extra labels to the podSweeper pod
##
podLabels: {}

##  podSweeper.containerSecurityContext Security context for the container
## Examples:
## containerSecurityContext:
##    runAsNonRoot: true
##    runAsUser: 1000
##    readOnlyRootFilesystem: true
containerSecurityContext: {}

## Configure extra options for the podSweeper containers' liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##  podSweeper.livenessProbe.enabled Enable livenessProbe on the podSweeper
##  podSweeper.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
##  podSweeper.livenessProbe.periodSeconds Period seconds for livenessProbe
##  podSweeper.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
##  podSweeper.livenessProbe.failureThreshold Failure threshold for livenessProbe
##  podSweeper.livenessProbe.successThreshold Success threshold for livenessProbe
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

##  podSweeper.readinessProbe.enabled Enable readinessProbe on the podSweeper
##  podSweeper.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
##  podSweeper.readinessProbe.periodSeconds Period seconds for readinessProbe
##  podSweeper.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
##  podSweeper.readinessProbe.failureThreshold Failure threshold for readinessProbe
##  podSweeper.readinessProbe.successThreshold Success threshold for readinessProbe
##
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

## Pod Sweeper app resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## We usually recommend not to specify default resources and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments with little
## resources, such as Minikube. If you do want to specify resources, uncomment the following
## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
##  podSweeper.resources.limits [object] The resources limits for the podSweeper container
##  podSweeper.resources.requests [object] The requested resources for the podSweeper container
resources:
  ## Example:
  ## limits:
  ##    cpu: 200m
  ##    memory: 1Gi
  limits: {}
  ## Examples:
  ## requests:
  ##    memory: 256Mi
  ##    cpu: 250m
  requests: {}

##  podSweeper.nodeSelector [object] Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

##  podSweeper.tolerations [array] Tolerations for podSweeper pod assignment.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

##  podSweeper.affinity [object] Affinity and anti-affinity for podSweeper pod assignment.
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

##  Pod TTLs in minutes
##  pod-sweeper will skip over pods with any status types with no TTL set (empty string)
##  Pod Status docs: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
##
##  podSweeper.timeToDeletePods.running Time to remove pods on running status (minutes).
##  podSweeper.timeToDeletePods.succeeded Time to remove pods on succeeded status (minutes).
##  podSweeper.timeToDeletePods.unsuccessful Time to remove pods on neither running nor succeeded status (minutes).
timeToDeletePods:
  running: ""
  succeeded: 10
  ## 2 hours - generally long enough for someone trying to reproduce an error to debug.
  unsuccessful: 120

replicaCount: 1

## namespace [string] namespace to deploy pod-sweeper at
namespace: ""
