export const enum Namespace {
  SOURCE = "Source",
  DESTINATION = "Destination",
  CONNECTION = "Connection",
  CONNECTOR = "Connector",
  ONBOARDING = "Onboarding",
  USER = "User",
  CONNECTOR_BUILDER = "ConnectorBuilder",
  SCHEMA = "Schema",
  ERD = "ERD",
  SETTINGS = "Settings",
  SYNC_QUESTIONNAIRE = "SyncQuestionnaire",
  STREAM_SELECTION = "StreamSelection",
  FORM = "Form",
  ENTERPRISE_SOURCE_STUB = "EnterpriseSourceStub",
  CONNECTIONS = "Connections",
  EMBEDDED = "Embedded",
}

export const enum Action {
  CREATE = "Create",
  TEST = "Test",
  SELECT = "Select",
  SUCCESS = "TestSuccess",
  FAILURE = "TestFailure",
  FREQUENCY = "FrequencySet",
  SYNC = "FullRefreshSync",
  EDIT_SCHEMA = "EditSchema",
  DISABLE = "Disable",
  REENABLE = "Reenable",
  DELETE = "Delete",
  REQUEST = "Request",
  SKIP = "Skip",
  PREFERENCES = "Preferences",
  NO_MATCHING_CONNECTOR = "NoMatchingConnector",
  SELECTION_OPENED = "SelectionOpened",
  INVITE = "Invite",
  OAUTH_ATTEMPT = "OAuthAttempt",
  OAUTH_SUCCESS = "OAuthSuccess",
  CREATE_OR_UPDATE_STATE = "CreateOrUpdateState",
  DOWNLOAD_SERVER_LOGS = "DownloadServerLogs",
  DOWNLOAD_SCHEDULER_LOGS = "DownloadSchedulerLogs",
  UPGRADE_VERSION = "UpgradeVersion",
  DISCOVER_SCHEMA = "DiscoverSchema",
  DISPLAYED = "Displayed",
  ANSWERED = "Answered",
  APPLIED = "Applied",
  SET_SYNC_MODE = "SetSyncMode",
  RATE_LIMITED = "RateLimited",
  DISMISSED_CHANGES_MODAL = "DismissedChangesModal",
  CONFIRMED_CANCEL_SYNC = "ConfirmedCancelSync",
  DECLINED_CANCEL_SYNC = "DeclinedCancelSync",
  SYNC_PROGRESS = "SyncProgress",

  // Connector Builder Actions
  CONNECTOR_BUILDER_START = "ConnectorBuilderStart",
  CONNECTOR_BUILDER_EDIT = "ConnectorBuilderEdit",
  API_URL_CREATE = "ApiUrlCreated",
  AUTHENTICATION_METHOD_SELECT = "AuthenticationMethodSelect",
  GLOBAL_CONFIGURATION_SELECT = "GlobalConfigurationSelect",
  COMPONENTS_SELECT = "ComponentsSelect",
  USER_INPUTS_SELECT = "UserInputsSelect",
  USER_INPUT_CREATE = "UserInputCreate",
  USER_INPUT_EDIT = "UserInputEdit",
  USER_INPUT_DELETE = "UserInputDelete",
  DYNAMIC_STREAM_SELECT = "DynamicStreamSelect",
  STREAM_SELECT = "StreamSelect",
  DYNAMIC_STREAM_CREATE = "DynamicStreamCreate",
  STREAM_CREATE = "StreamCreate",
  STREAM_COPY = "StreamCopy",
  STREAM_DELETE = "StreamDelete",
  DYNAMIC_STREAM_DELETE = "DynamicStreamDelete",
  DYNAMIC_STREAM_GENERATE = "DynamicStreamGenerate",
  DYNAMIC_STREAM_PREVIEW_ENDPOINT = "DynamicStreamPreviewEndpoint",
  STREAM_TEST = "StreamTest",
  STREAM_TEST_SUCCESS = "StreamTestSuccess",
  STREAM_TEST_FAILURE = "StreamTestFailure",
  RESET_ALL = "ResetAll",
  DOWNLOAD_YAML = "DownloadYaml",
  TOGGLE_UI_YAML = "ToggleUiYaml",
  YAML_TO_UI_CONVERSION_FAILURE = "YamlToUiConversionFailure",
  DISCARD_YAML_CHANGES = "DiscardYamlChanges",
  OVERWRITE_SCHEMA = "OverwriteSchema",
  MERGE_SCHEMA = "MergeSchema",
  UI_INCOMPATIBLE_YAML_IMPORTED = "UiIncompatibleYamlImported",
  UI_COMPATIBLE_YAML_IMPORTED = "UiCompatibleYamlImported",
  YAML_IMPORTED = "YamlImported",
  INVALID_YAML_UPLOADED = "InvalidYamlUploaded",
  START_FROM_SCRATCH = "StartFromScratch",
  CHANGE_PROJECT_VERSION = "ChangeProjectVersion",
  PUBLISH_PROJECT = "PublishProject",
  RELEASE_NEW_PROJECT_VERSION = "ReleaseNewProjectVersion",
  CONNECTOR_BUILDER_DELETE = "ConnectorBuilderDelete",
  CONTRIBUTE_FORM_FOCUSED = "ContributeFormFocused",
  CONTRIBUTE_SUCCESS = "ContributeSuccess",
  CONTRIBUTE_FAILURE = "ContributeFailure",
  PUBLISH_DROPDOWN_SELECTED = "PublishDropdownSelected",
  PUBLISH_RADIO_BUTTON_SELECTED = "PublishRadioButtonSelected",

  // Connector Builder Actions
  CONNECTOR_BUILDER_ASSIST_CONFIG_OPENED = "ConnectorBuilderAssistConfigOpened",
  CONNECTOR_BUILDER_ASSIST_CONFIG_CLOSED = "ConnectorBuilderAssistConfigClosed",
  CONNECTOR_BUILDER_ASSIST_ENABLED = "ConnectorBuilderAssistEnabled",
  CONNECTOR_BUILDER_ASSIST_DISABLED = "ConnectorBuilderAssistDisabled",
  CONNECTOR_BUILDER_ASSIST_SUGGESTION_VIEWED = "ConnectorBuilderAssistSuggestionViewed",
  CONNECTOR_BUILDER_ASSIST_SUGGESTION_ACCEPTED = "ConnectorBuilderAssistSuggestionAccepted",

  // Connections Actions
  CONNECTIONS_GRAPH_DRAWER_OPENED = "ConnectionGraphDrawerOpened",
  CONNECTIONS_GRAPH_DRAWER_LOADED = "ConnectionGraphDrawerLoaded",
  SYNC_FAILURE_EXPLANATION_OPENED = "SyncFailureExplanationOpened",
  REFRESH_FAILURE_EXPLANATION_OPENED = "RefreshFailureExplanationOpened",

  // Embedded Onboarding Actions
  DESTINATION_SELECTED = "DestinationSelected",
  CONNECTION_TEMPLATE_CREATED = "ConnectionTemplateCreated",
  CONNECTION_TEMPLATE_CREATE_FAILED = "ConnectionTemplateCreateFailed",
  BACK_TO_SELECT_DESTINATION = "BackToSelectDestination",
}

export type EventParams = Record<string, unknown>;
