
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Common Configuration
*/}}

{{/*
Renders the edition value
*/}}
{{- define "airbyte-data-plane.common.edition" }}
    {{- .Values.edition | default "community" }}
{{- end }}

{{/*
Renders the common.edition environment variable
*/}}
{{- define "airbyte-data-plane.common.edition.env" }}
- name: AIRBYTE_EDITION
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AIRBYTE_EDITION
{{- end }}

{{/*
Renders the version value
*/}}
{{- define "airbyte-data-plane.common.version" }}
    {{- .Values.version | default .Chart.AppVersion }}
{{- end }}

{{/*
Renders the common.version environment variable
*/}}
{{- define "airbyte-data-plane.common.version.env" }}
- name: AIRBYTE_VERSION
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AIRBYTE_VERSION
{{- end }}

{{/*
Renders the airbyteUrl value
*/}}
{{- define "airbyte-data-plane.common.airbyteUrl" }}
    {{- .Values.airbyteUrl }}
{{- end }}

{{/*
Renders the common.airbyteUrl environment variable
*/}}
{{- define "airbyte-data-plane.common.airbyteUrl.env" }}
- name: AIRBYTE_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AIRBYTE_URL
{{- end }}

{{/*
Renders the api.authEnabled value
*/}}
{{- define "airbyte-data-plane.common.api.authEnabled" }}
	{{- if eq .Values.api.authEnabled nil }}
    	{{- true }}
	{{- else }}
    	{{- .Values.api.authEnabled }}
	{{- end }}
{{- end }}

{{/*
Renders the common.api.authEnabled environment variable
*/}}
{{- define "airbyte-data-plane.common.api.authEnabled.env" }}
- name: API_AUTHORIZATION_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: API_AUTHORIZATION_ENABLED
{{- end }}

{{/*
Renders the api.internalHost value
*/}}
{{- define "airbyte-data-plane.common.api.internalHost" }}
    {{- .Values.api.internalHost | default (include "airbyte-data-plane.common.airbyteUrl" .) }}
{{- end }}

{{/*
Renders the common.api.internalHost environment variable
*/}}
{{- define "airbyte-data-plane.common.api.internalHost.env" }}
- name: INTERNAL_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: INTERNAL_API_HOST
{{- end }}

{{/*
Renders the local value
*/}}
{{- define "airbyte-data-plane.common.local" }}
	{{- if eq .Values.local nil }}
    	{{- false }}
	{{- else }}
    	{{- .Values.local }}
	{{- end }}
{{- end }}

{{/*
Renders the common.local environment variable
*/}}
{{- define "airbyte-data-plane.common.local.env" }}
- name: LOCAL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: LOCAL
{{- end }}

{{/*
Renders the set of all common environment variables
*/}}
{{- define "airbyte-data-plane.common.envs" }}
{{- include "airbyte-data-plane.common.edition.env" . }}
{{- include "airbyte-data-plane.common.version.env" . }}
{{- include "airbyte-data-plane.common.airbyteUrl.env" . }}
{{- include "airbyte-data-plane.common.api.authEnabled.env" . }}
{{- include "airbyte-data-plane.common.api.internalHost.env" . }}
{{- include "airbyte-data-plane.common.local.env" . }}
{{- end }}

{{/*
Renders the set of all common config map variables
*/}}
{{- define "airbyte-data-plane.common.configVars" }}
AIRBYTE_EDITION: {{ include "airbyte-data-plane.common.edition" . | quote }}
AIRBYTE_VERSION: {{ include "airbyte-data-plane.common.version" . | quote }}
AIRBYTE_URL: {{ include "airbyte-data-plane.common.airbyteUrl" . | quote }}
API_AUTHORIZATION_ENABLED: {{ include "airbyte-data-plane.common.api.authEnabled" . | quote }}
INTERNAL_API_HOST: {{ include "airbyte-data-plane.common.api.internalHost" . | quote }}
LOCAL: {{ include "airbyte-data-plane.common.local" . | quote }}
{{- end }}
