
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Dataplane Configuration
*/}}

{{/*
Renders the dataPlane.id value
*/}}
{{- define "airbyte-data-plane.dataPlane.id" }}
    {{- .Values.dataPlane.id | default "local" }}
{{- end }}

{{/*
Renders the dataPlane.id environment variable
*/}}
{{- define "airbyte-data-plane.dataPlane.id.env" }}
- name: DATA_PLANE_ID
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: DATA_PLANE_ID
{{- end }}

{{/*
Renders the dataPlane.controlPlaneAuthEndpoint value
*/}}
{{- define "airbyte-data-plane.dataPlane.controlPlaneAuthEndpoint" }}
    {{- .Values.dataPlane.controlPlaneAuthEndpoint | default (include "airbyte-data-plane.common.airbyteUrl" .) }}
{{- end }}

{{/*
Renders the dataPlane.controlPlaneAuthEndpoint environment variable
*/}}
{{- define "airbyte-data-plane.dataPlane.controlPlaneAuthEndpoint.env" }}
- name: CONTROL_PLANE_AUTH_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: CONTROL_PLANE_AUTH_ENDPOINT
{{- end }}

{{/*
Renders the dataPlane.serviceAccountEmail value
*/}}
{{- define "airbyte-data-plane.dataPlane.serviceAccountEmail" }}
    {{- .Values.dataPlane.serviceAccountEmail }}
{{- end }}

{{/*
Renders the dataPlane.serviceAccountEmail environment variable
*/}}
{{- define "airbyte-data-plane.dataPlane.serviceAccountEmail.env" }}
- name: DATA_PLANE_SERVICE_ACCOUNT_EMAIL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: DATA_PLANE_SERVICE_ACCOUNT_EMAIL
{{- end }}

{{/*
Renders the dataPlane.serviceAccountCredentialsPath value
*/}}
{{- define "airbyte-data-plane.dataPlane.serviceAccountCredentialsPath" }}
    {{- .Values.dataPlane.serviceAccountCredentialsPath | default "/secrets/dataplane-creds/sa.json" }}
{{- end }}

{{/*
Renders the dataPlane.serviceAccountCredentialsPath environment variable
*/}}
{{- define "airbyte-data-plane.dataPlane.serviceAccountCredentialsPath.env" }}
- name: DATA_PLANE_SERVICE_ACCOUNT_CREDENTIALS_PATH
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: DATA_PLANE_SERVICE_ACCOUNT_CREDENTIALS_PATH
{{- end }}

{{/*
Renders the set of all dataPlane environment variables
*/}}
{{- define "airbyte-data-plane.dataPlane.envs" }}
{{- include "airbyte-data-plane.dataPlane.id.env" . }}
{{- include "airbyte-data-plane.dataPlane.controlPlaneAuthEndpoint.env" . }}
{{- include "airbyte-data-plane.dataPlane.serviceAccountEmail.env" . }}
{{- include "airbyte-data-plane.dataPlane.serviceAccountCredentialsPath.env" . }}
{{- end }}

{{/*
Renders the set of all dataPlane config map variables
*/}}
{{- define "airbyte-data-plane.dataPlane.configVars" }}
DATA_PLANE_ID: {{ include "airbyte-data-plane.dataPlane.id" . | quote }}
CONTROL_PLANE_AUTH_ENDPOINT: {{ include "airbyte-data-plane.dataPlane.controlPlaneAuthEndpoint" . | quote }}
DATA_PLANE_SERVICE_ACCOUNT_EMAIL: {{ include "airbyte-data-plane.dataPlane.serviceAccountEmail" . | quote }}
DATA_PLANE_SERVICE_ACCOUNT_CREDENTIALS_PATH: {{ include "airbyte-data-plane.dataPlane.serviceAccountCredentialsPath" . | quote }}
{{- end }}
