
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Keycloak Configuration
*/}}

{{/*
Renders the keycloak.host value
*/}}
{{- define "airbyte-data-plane.keycloak.client.host" }}
    {{- (get (urlParse .Values.airbyteUrl) "host") }}
{{- end }}

{{/*
Renders the keycloak.client.host environment variable
*/}}
{{- define "airbyte-data-plane.keycloak.client.host.env" }}
- name: KEYCLOAK_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: KEYCLOAK_HOST
{{- end }}

{{/*
Renders the keycloak.internalRealm value
*/}}
{{- define "airbyte-data-plane.keycloak.client.internalRealm" }}
    {{- .Values.keycloak.internalRealm | default "_airbyte-internal" }}
{{- end }}

{{/*
Renders the keycloak.client.internalRealm environment variable
*/}}
{{- define "airbyte-data-plane.keycloak.client.internalRealm.env" }}
- name: KEYCLOAK_INTERNAL_REALM
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: KEYCLOAK_INTERNAL_REALM
{{- end }}

{{/*
Renders the keycloak.realmIssuer value
*/}}
{{- define "airbyte-data-plane.keycloak.client.realmIssuer" }}
    {{- (printf "%s/auth/realms/%s" (include "airbyte-data-plane.common.airbyteUrl" .) (include "airbyte-data-plane.keycloak.client.internalRealm" .)) }}
{{- end }}

{{/*
Renders the keycloak.client.realmIssuer environment variable
*/}}
{{- define "airbyte-data-plane.keycloak.client.realmIssuer.env" }}
- name: KEYCLOAK_INTERNAL_REALM_ISSUER
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: KEYCLOAK_INTERNAL_REALM_ISSUER
{{- end }}

{{/*
Renders the keycloak.protocol value
*/}}
{{- define "airbyte-data-plane.keycloak.client.protocol" }}
    {{- .Values.keycloak.protocol | default "https" }}
{{- end }}

{{/*
Renders the keycloak.client.protocol environment variable
*/}}
{{- define "airbyte-data-plane.keycloak.client.protocol.env" }}
- name: KEYCLOAK_PROTOCOL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: KEYCLOAK_PROTOCOL
{{- end }}

{{/*
Renders the set of all keycloak.client environment variables
*/}}
{{- define "airbyte-data-plane.keycloak.client.envs" }}
{{- include "airbyte-data-plane.keycloak.client.host.env" . }}
{{- include "airbyte-data-plane.keycloak.client.internalRealm.env" . }}
{{- include "airbyte-data-plane.keycloak.client.realmIssuer.env" . }}
{{- include "airbyte-data-plane.keycloak.client.protocol.env" . }}
{{- end }}

{{/*
Renders the set of all keycloak.client config map variables
*/}}
{{- define "airbyte-data-plane.keycloak.client.configVars" }}
KEYCLOAK_HOST: {{ include "airbyte-data-plane.keycloak.client.host" . | quote }}
KEYCLOAK_INTERNAL_REALM: {{ include "airbyte-data-plane.keycloak.client.internalRealm" . | quote }}
KEYCLOAK_INTERNAL_REALM_ISSUER: {{ include "airbyte-data-plane.keycloak.client.realmIssuer" . | quote }}
KEYCLOAK_PROTOCOL: {{ include "airbyte-data-plane.keycloak.client.protocol" . | quote }}
{{- end }}
