
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Metrics Configuration
*/}}

{{/*
Renders the metrics.enabled value
*/}}
{{- define "airbyte-data-plane.metrics.enabled" }}
	{{- if eq .Values.metrics.enabled nil }}
    	{{- false }}
	{{- else }}
    	{{- .Values.metrics.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the metrics.enabled environment variable
*/}}
{{- define "airbyte-data-plane.metrics.enabled.env" }}
- name: MICROMETER_METRICS_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MICROMETER_METRICS_ENABLED
{{- end }}

{{/*
Renders the metrics.step value
*/}}
{{- define "airbyte-data-plane.metrics.step" }}
    {{- .Values.metrics.step | default "PT1M" }}
{{- end }}

{{/*
Renders the metrics.step environment variable
*/}}
{{- define "airbyte-data-plane.metrics.step.env" }}
- name: MICROMETER_METRICS_STEP
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MICROMETER_METRICS_STEP
{{- end }}

{{/*
Renders the metrics.statsd.flavor value
*/}}
{{- define "airbyte-data-plane.metrics.statsd.flavor" }}
    {{- .Values.metrics.statsd.flavor | default "datadog" }}
{{- end }}

{{/*
Renders the metrics.statsd.flavor environment variable
*/}}
{{- define "airbyte-data-plane.metrics.statsd.flavor.env" }}
- name: MICROMETER_METRICS_STATSD_FLAVOR
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MICROMETER_METRICS_STATSD_FLAVOR
{{- end }}

{{/*
Renders the metrics.otlp.enabled value
*/}}
{{- define "airbyte-data-plane.metrics.otlp.enabled" }}
	{{- if eq .Values.metrics.otlp.enabled nil }}
    	{{- false }}
	{{- else }}
    	{{- .Values.metrics.otlp.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the metrics.otlp.enabled environment variable
*/}}
{{- define "airbyte-data-plane.metrics.otlp.enabled.env" }}
- name: MICROMETER_METRICS_OTLP_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MICROMETER_METRICS_OTLP_ENABLED
{{- end }}

{{/*
Renders the metrics.otlp.collectorEndpoint value
*/}}
{{- define "airbyte-data-plane.metrics.otlp.collectorEndpoint" }}
    {{- .Values.metrics.otlp.collectorEndpoint }}
{{- end }}

{{/*
Renders the metrics.otlp.collectorEndpoint environment variable
*/}}
{{- define "airbyte-data-plane.metrics.otlp.collectorEndpoint.env" }}
- name: OTEL_COLLECTOR_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: OTEL_COLLECTOR_ENDPOINT
{{- end }}

{{/*
Renders the metrics.statsd.enabled value
*/}}
{{- define "airbyte-data-plane.metrics.statsd.enabled" }}
	{{- if eq .Values.metrics.statsd.enabled nil }}
    	{{- false }}
	{{- else }}
    	{{- .Values.metrics.statsd.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the metrics.statsd.enabled environment variable
*/}}
{{- define "airbyte-data-plane.metrics.statsd.enabled.env" }}
- name: MICROMETER_METRICS_STATSD_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MICROMETER_METRICS_STATSD_ENABLED
{{- end }}

{{/*
Renders the metrics.statsd.host value
*/}}
{{- define "airbyte-data-plane.metrics.statsd.host" }}
    {{- .Values.metrics.statsd.host }}
{{- end }}

{{/*
Renders the metrics.statsd.host environment variable
*/}}
{{- define "airbyte-data-plane.metrics.statsd.host.env" }}
- name: STATSD_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
    
{{- end }}

{{/*
Renders the metrics.statsd.port value
*/}}
{{- define "airbyte-data-plane.metrics.statsd.port" }}
    {{- .Values.metrics.statsd.port | default 8125 }}
{{- end }}

{{/*
Renders the metrics.statsd.port environment variable
*/}}
{{- define "airbyte-data-plane.metrics.statsd.port.env" }}
- name: STATSD_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: STATSD_PORT
{{- end }}

{{/*
Renders the set of all metrics environment variables
*/}}
{{- define "airbyte-data-plane.metrics.envs" }}
{{- include "airbyte-data-plane.metrics.enabled.env" . }}
{{- include "airbyte-data-plane.metrics.step.env" . }}
{{- include "airbyte-data-plane.metrics.statsd.flavor.env" . }}
{{- include "airbyte-data-plane.metrics.otlp.enabled.env" . }}
{{- include "airbyte-data-plane.metrics.otlp.collectorEndpoint.env" . }}
{{- include "airbyte-data-plane.metrics.statsd.enabled.env" . }}
{{- include "airbyte-data-plane.metrics.statsd.host.env" . }}
{{- include "airbyte-data-plane.metrics.statsd.port.env" . }}
{{- end }}

{{/*
Renders the set of all metrics config map variables
*/}}
{{- define "airbyte-data-plane.metrics.configVars" }}
MICROMETER_METRICS_ENABLED: {{ include "airbyte-data-plane.metrics.enabled" . | quote }}
MICROMETER_METRICS_STEP: {{ include "airbyte-data-plane.metrics.step" . | quote }}
MICROMETER_METRICS_STATSD_FLAVOR: {{ include "airbyte-data-plane.metrics.statsd.flavor" . | quote }}
MICROMETER_METRICS_OTLP_ENABLED: {{ include "airbyte-data-plane.metrics.otlp.enabled" . | quote }}
OTEL_COLLECTOR_ENDPOINT: {{ include "airbyte-data-plane.metrics.otlp.collectorEndpoint" . | quote }}
MICROMETER_METRICS_STATSD_ENABLED: {{ include "airbyte-data-plane.metrics.statsd.enabled" . | quote }}
STATSD_HOST: {{ include "airbyte-data-plane.metrics.statsd.host" . | quote }}
STATSD_PORT: {{ include "airbyte-data-plane.metrics.statsd.port" . | quote }}
{{- end }}
