
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Micronaut Configuration
*/}}

{{/*
Renders the micronaut.environments value
*/}}
{{- define "airbyte-data-plane.micronaut.environments" }}
    {{- join "," (concat .Values.micronaut.environments (list "data-plane")) }}
{{- end }}

{{/*
Renders the micronaut.environments environment variable
*/}}
{{- define "airbyte-data-plane.micronaut.environments.env" }}
- name: MICRONAUT_ENVIRONMENTS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MICRONAUT_ENVIRONMENTS
{{- end }}

{{/*
Renders the set of all micronaut environment variables
*/}}
{{- define "airbyte-data-plane.micronaut.envs" }}
{{- include "airbyte-data-plane.micronaut.environments.env" . }}
{{- end }}

{{/*
Renders the set of all micronaut config map variables
*/}}
{{- define "airbyte-data-plane.micronaut.configVars" }}
MICRONAUT_ENVIRONMENTS: {{ include "airbyte-data-plane.micronaut.environments" . | quote }}
{{- end }}
