
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Secretsmanager Configuration
*/}}

{{/*
Renders the secretsManager secret name
*/}}
{{- define "airbyte-data-plane.secretsManager.secretName" }}
{{- if .Values.secretsManager.secretName }}
    {{- .Values.secretsManager.secretName }}
{{- else }}
    {{- .Values.secretName | default (printf "%s-airbyte-data-plane-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the secretsManager.type value
*/}}
{{- define "airbyte-data-plane.secretsManager.type" }}
    {{- .Values.secretsManager.type | default "vault" }}
{{- end }}

{{/*
Renders the secretsManager.type environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.type.env" }}
- name: SECRET_PERSISTENCE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: SECRET_PERSISTENCE
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.accessKeyId value
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.accessKeyId" }}
    {{- .Values.secretsManager.awsSecretManager.accessKeyId }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.accessKeyId secret key
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.accessKeyId.secretKey" }}
	{{- .Values.secretsManager.awsSecretManager.accessKeyIdSecretKey | default "AWS_SECRET_MANAGER_ACCESS_KEY_ID" }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.accessKeyId environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.accessKeyId.env" }}
- name: AWS_SECRET_MANAGER_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.secretsManager.secretName" . }}
      key: {{ include "airbyte-data-plane.secretsManager.awsSecretManager.accessKeyId.secretKey" . }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.secretAccessKey value
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.secretAccessKey" }}
    {{- .Values.secretsManager.awsSecretManager.secretAccessKey }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.secretAccessKey secret key
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.secretAccessKey.secretKey" }}
	{{- .Values.secretsManager.awsSecretManager.secretAccessKeySecretKey | default "AWS_SECRET_MANAGER_SECRET_ACCESS_KEY" }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.secretAccessKey environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.secretAccessKey.env" }}
- name: AWS_SECRET_MANAGER_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.secretsManager.secretName" . }}
      key: {{ include "airbyte-data-plane.secretsManager.awsSecretManager.secretAccessKey.secretKey" . }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.region value
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.region" }}
    {{- .Values.secretsManager.awsSecretManager.region }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.region environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.region.env" }}
- name: AWS_SECRET_MANAGER_REGION
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AWS_SECRET_MANAGER_REGION
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.tags value
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.tags" }}
    {{- include "airbyte-data-plane.tagsToString" .Values.secretsManager.awsSecretManager.tags }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.tags environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.tags.env" }}
- name: AWS_SECRET_MANAGER_SECRET_TAGS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AWS_SECRET_MANAGER_SECRET_TAGS
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.kmsArn value
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.kmsArn" }}
    {{- .Values.secretsManager.awsSecretManager.kmsArn | default "" }}
{{- end }}

{{/*
Renders the secretsManager.awsSecretManager.kmsArn environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.awsSecretManager.kmsArn.env" }}
- name: AWS_KMS_KEY_ARN
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AWS_KMS_KEY_ARN
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientId value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientId" }}
    {{- .Values.secretsManager.azureKeyVault.clientId }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientId secret key
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientId.secretKey" }}
	{{- .Values.secretsManager.azureKeyVault.clientIdSecretKey | default "AB_AZURE_KEY_VAULT_CLIENT_ID" }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientId environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientId.env" }}
- name: AB_AZURE_KEY_VAULT_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.secretsManager.secretName" . }}
      key: {{ include "airbyte-data-plane.secretsManager.azureKeyVault.clientId.secretKey" . }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecret value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecret" }}
    {{- .Values.secretsManager.azureKeyVault.clientSecret }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecret secret key
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecret.secretKey" }}
	{{- .Values.secretsManager.azureKeyVault.clientSecretSecretKey | default "AB_AZURE_KEY_VAULT_CLIENT_SECRET" }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecret environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecret.env" }}
- name: AB_AZURE_KEY_VAULT_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.secretsManager.secretName" . }}
      key: {{ include "airbyte-data-plane.secretsManager.azureKeyVault.clientSecret.secretKey" . }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.tenantId value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.tenantId" }}
    {{- .Values.secretsManager.azureKeyVault.tenantId }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.tenantId environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.tenantId.env" }}
- name: AB_AZURE_KEY_VAULT_TENANT_ID
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AB_AZURE_KEY_VAULT_TENANT_ID
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.vaultUrl value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.vaultUrl" }}
    {{- .Values.secretsManager.azureKeyVault.vaultUrl }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.vaultUrl environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.vaultUrl.env" }}
- name: AB_AZURE_KEY_VAULT_VAULT_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AB_AZURE_KEY_VAULT_VAULT_URL
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientIdRefName value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientIdRefName" }}
    {{- include "airbyte-data-plane.secretsManager.secretName" . }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientIdRefName environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientIdRefName.env" }}
- name: AB_AZURE_KEY_CLIENT_ID_REF_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AB_AZURE_KEY_CLIENT_ID_REF_NAME
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientIdRefKey value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientIdRefKey" }}
    {{- .Values.secretsManager.azureKeyVault.clientIdSecretKey | default "AB_AZURE_KEY_VAULT_CLIENT_ID" }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientIdRefKey environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientIdRefKey.env" }}
- name: AB_AZURE_KEY_CLIENT_ID_REF_KEY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AB_AZURE_KEY_CLIENT_ID_REF_KEY
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecretRefName value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecretRefName" }}
    {{- include "airbyte-data-plane.secretsManager.secretName" . }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecretRefName environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecretRefName.env" }}
- name: AB_AZURE_KEY_CLIENT_SECRET_REF_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AB_AZURE_KEY_CLIENT_SECRET_REF_NAME
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecretRefKey value
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecretRefKey" }}
    {{- .Values.secretsManager.azureKeyVault.clientSecretSecretKey | default "AB_AZURE_KEY_VAULT_CLIENT_SECRET" }}
{{- end }}

{{/*
Renders the secretsManager.azureKeyVault.clientSecretRefKey environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.azureKeyVault.clientSecretRefKey.env" }}
- name: AB_AZURE_KEY_CLIENT_SECRET_REF_KEY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AB_AZURE_KEY_CLIENT_SECRET_REF_KEY
{{- end }}

{{/*
Renders the secretsManager.googleSecretManager.projectId value
*/}}
{{- define "airbyte-data-plane.secretsManager.googleSecretManager.projectId" }}
    {{- .Values.secretsManager.googleSecretManager.projectId }}
{{- end }}

{{/*
Renders the secretsManager.googleSecretManager.projectId environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.googleSecretManager.projectId.env" }}
- name: SECRET_STORE_GCP_PROJECT_ID
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: SECRET_STORE_GCP_PROJECT_ID
{{- end }}

{{/*
Renders the secretsManager.googleSecretManager.credentials value
*/}}
{{- define "airbyte-data-plane.secretsManager.googleSecretManager.credentials" }}
    {{- .Values.secretsManager.googleSecretManager.credentials }}
{{- end }}

{{/*
Renders the secretsManager.googleSecretManager.credentials secret key
*/}}
{{- define "airbyte-data-plane.secretsManager.googleSecretManager.credentials.secretKey" }}
	{{- .Values.secretsManager.googleSecretManager.credentialsSecretKey | default "SECRET_STORE_GCP_CREDENTIALS" }}
{{- end }}

{{/*
Renders the secretsManager.googleSecretManager.credentials environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.googleSecretManager.credentials.env" }}
- name: SECRET_STORE_GCP_CREDENTIALS
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.secretsManager.secretName" . }}
      key: {{ include "airbyte-data-plane.secretsManager.googleSecretManager.credentials.secretKey" . }}
{{- end }}

{{/*
Renders the secretsManager.vault.address value
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.address" }}
    {{- .Values.secretsManager.vault.address | default (printf "http://airbyte-vault-svc.%s:8200" .Release.Namespace) }}
{{- end }}

{{/*
Renders the secretsManager.vault.address environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.address.env" }}
- name: VAULT_ADDRESS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: VAULT_ADDRESS
{{- end }}

{{/*
Renders the secretsManager.vault.prefix value
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.prefix" }}
    {{- .Values.secretsManager.vault.prefix | default "secret/" }}
{{- end }}

{{/*
Renders the secretsManager.vault.prefix environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.prefix.env" }}
- name: VAULT_PREFIX
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: VAULT_PREFIX
{{- end }}

{{/*
Renders the secretsManager.vault.authToken value
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.authToken" }}
    {{- .Values.secretsManager.vault.authToken }}
{{- end }}

{{/*
Renders the secretsManager.vault.authToken secret key
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.authToken.secretKey" }}
	{{- .Values.secretsManager.vault.authTokenSecretKey | default "VAULT_AUTH_TOKEN" }}
{{- end }}

{{/*
Renders the secretsManager.vault.authToken environment variable
*/}}
{{- define "airbyte-data-plane.secretsManager.vault.authToken.env" }}
- name: VAULT_AUTH_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.secretsManager.secretName" . }}
      key: {{ include "airbyte-data-plane.secretsManager.vault.authToken.secretKey" . }}
{{- end }}

{{/*
Renders the set of all secretsManager environment variables
*/}}
{{- define "airbyte-data-plane.secretsManager.envs" }}
{{- include "airbyte-data-plane.secretsManager.type.env" . }}
{{- $opt := (include "airbyte-data-plane.secretsManager.type" .) }}

{{- if eq $opt "AWS_SECRET_MANAGER" }}
{{- include "airbyte-data-plane.secretsManager.awsSecretManager.accessKeyId.env" . }}
{{- include "airbyte-data-plane.secretsManager.awsSecretManager.secretAccessKey.env" . }}
{{- include "airbyte-data-plane.secretsManager.awsSecretManager.region.env" . }}
{{- include "airbyte-data-plane.secretsManager.awsSecretManager.tags.env" . }}
{{- include "airbyte-data-plane.secretsManager.awsSecretManager.kmsArn.env" . }}
{{- end }}

{{- if eq $opt "AZURE_KEY_VAULT" }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.clientId.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.clientSecret.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.tenantId.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.vaultUrl.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.clientIdRefName.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.clientIdRefKey.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.clientSecretRefName.env" . }}
{{- include "airbyte-data-plane.secretsManager.azureKeyVault.clientSecretRefKey.env" . }}
{{- end }}

{{- if eq $opt "GOOGLE_SECRET_MANAGER" }}
{{- include "airbyte-data-plane.secretsManager.googleSecretManager.projectId.env" . }}
{{- include "airbyte-data-plane.secretsManager.googleSecretManager.credentials.env" . }}
{{- end }}

{{- if eq $opt "TESTING_CONFIG_DB_TABLE" }}
{{- end }}

{{- if eq $opt "VAULT" }}
{{- include "airbyte-data-plane.secretsManager.vault.address.env" . }}
{{- include "airbyte-data-plane.secretsManager.vault.prefix.env" . }}
{{- include "airbyte-data-plane.secretsManager.vault.authToken.env" . }}
{{- end }}

{{- end }}

{{/*
Renders the set of all secretsManager config map variables
*/}}
{{- define "airbyte-data-plane.secretsManager.configVars" }}
SECRET_PERSISTENCE: {{ include "airbyte-data-plane.secretsManager.type" . | quote }}
{{- $opt := (include "airbyte-data-plane.secretsManager.type" .) }}

{{- if eq $opt "AWS_SECRET_MANAGER" }}
AWS_SECRET_MANAGER_REGION: {{ include "airbyte-data-plane.secretsManager.awsSecretManager.region" . | quote }}
AWS_SECRET_MANAGER_SECRET_TAGS: {{ include "airbyte-data-plane.tagsToString" .Values.secretsManager.awsSecretManager.tags | quote }}
AWS_KMS_KEY_ARN: {{ include "airbyte-data-plane.secretsManager.awsSecretManager.kmsArn" . | quote }}
{{- end }}

{{- if eq $opt "AZURE_KEY_VAULT" }}
AB_AZURE_KEY_VAULT_TENANT_ID: {{ include "airbyte-data-plane.secretsManager.azureKeyVault.tenantId" . | quote }}
AB_AZURE_KEY_VAULT_VAULT_URL: {{ include "airbyte-data-plane.secretsManager.azureKeyVault.vaultUrl" . | quote }}
AB_AZURE_KEY_CLIENT_ID_REF_NAME: {{ include "airbyte-data-plane.secretsManager.secretName" . | quote }}
AB_AZURE_KEY_CLIENT_ID_REF_KEY: {{ .Values.secretsManager.azureKeyVault.clientIdSecretKey | default "AB_AZURE_KEY_VAULT_CLIENT_ID" | quote }}
AB_AZURE_KEY_CLIENT_SECRET_REF_NAME: {{ include "airbyte-data-plane.secretsManager.secretName" . | quote }}
AB_AZURE_KEY_CLIENT_SECRET_REF_KEY: {{ .Values.secretsManager.azureKeyVault.clientSecretSecretKey | default "AB_AZURE_KEY_VAULT_CLIENT_SECRET" | quote }}
{{- end }}

{{- if eq $opt "GOOGLE_SECRET_MANAGER" }}
SECRET_STORE_GCP_PROJECT_ID: {{ include "airbyte-data-plane.secretsManager.googleSecretManager.projectId" . | quote }}
{{- end }}

{{- if eq $opt "TESTING_CONFIG_DB_TABLE" }}
{{- end }}

{{- if eq $opt "VAULT" }}
VAULT_ADDRESS: {{ include "airbyte-data-plane.secretsManager.vault.address" . | quote }}
VAULT_PREFIX: {{ include "airbyte-data-plane.secretsManager.vault.prefix" . | quote }}
{{- end }}

{{- end }}

{{/*
Renders the set of all secretsManager secret variables
*/}}
{{- define "airbyte-data-plane.secretsManager.secrets" }}
{{- $opt := (include "airbyte-data-plane.secretsManager.type" .) }}

{{- if eq $opt "AWS_SECRET_MANAGER" }}
AWS_SECRET_MANAGER_ACCESS_KEY_ID: {{ include "airbyte-data-plane.secretsManager.awsSecretManager.accessKeyId" . | quote }}
AWS_SECRET_MANAGER_SECRET_ACCESS_KEY: {{ include "airbyte-data-plane.secretsManager.awsSecretManager.secretAccessKey" . | quote }}
{{- end }}

{{- if eq $opt "AZURE_KEY_VAULT" }}
AB_AZURE_KEY_VAULT_CLIENT_ID: {{ include "airbyte-data-plane.secretsManager.azureKeyVault.clientId" . | quote }}
AB_AZURE_KEY_VAULT_CLIENT_SECRET: {{ include "airbyte-data-plane.secretsManager.azureKeyVault.clientSecret" . | quote }}
{{- end }}

{{- if eq $opt "GOOGLE_SECRET_MANAGER" }}
SECRET_STORE_GCP_CREDENTIALS: {{ include "airbyte-data-plane.secretsManager.googleSecretManager.credentials" . | quote }}
{{- end }}

{{- if eq $opt "TESTING_CONFIG_DB_TABLE" }}
{{- end }}

{{- if eq $opt "VAULT" }}
VAULT_AUTH_TOKEN: {{ include "airbyte-data-plane.secretsManager.vault.authToken" . | quote }}
{{- end }}

{{- end }}
