
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Storage Configuration
*/}}

{{/*
Renders the storage secret name
*/}}
{{- define "airbyte-data-plane.storage.secretName" }}
{{- if .Values.storage.secretName }}
    {{- .Values.storage.secretName }}
{{- else }}
    {{- .Values.secretName | default (printf "%s-airbyte-data-plane-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the storage.type value
*/}}
{{- define "airbyte-data-plane.storage.type" }}
    {{- .Values.storage.type | default "minio" }}
{{- end }}

{{/*
Renders the storage.type environment variable
*/}}
{{- define "airbyte-data-plane.storage.type.env" }}
- name: STORAGE_TYPE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: STORAGE_TYPE
{{- end }}

{{/*
Renders the storage.bucket.activityPayload value
*/}}
{{- define "airbyte-data-plane.storage.bucket.activityPayload" }}
    {{- .Values.storage.bucket.activityPayload | default "airbyte-storage" }}
{{- end }}

{{/*
Renders the storage.bucket.activityPayload environment variable
*/}}
{{- define "airbyte-data-plane.storage.bucket.activityPayload.env" }}
- name: STORAGE_BUCKET_ACTIVITY_PAYLOAD
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: STORAGE_BUCKET_ACTIVITY_PAYLOAD
{{- end }}

{{/*
Renders the storage.bucket.log value
*/}}
{{- define "airbyte-data-plane.storage.bucket.log" }}
    {{- .Values.storage.bucket.log | default "airbyte-storage" }}
{{- end }}

{{/*
Renders the storage.bucket.log environment variable
*/}}
{{- define "airbyte-data-plane.storage.bucket.log.env" }}
- name: STORAGE_BUCKET_LOG
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: STORAGE_BUCKET_LOG
{{- end }}

{{/*
Renders the storage.bucket.state value
*/}}
{{- define "airbyte-data-plane.storage.bucket.state" }}
    {{- .Values.storage.bucket.state | default "airbyte-storage" }}
{{- end }}

{{/*
Renders the storage.bucket.state environment variable
*/}}
{{- define "airbyte-data-plane.storage.bucket.state.env" }}
- name: STORAGE_BUCKET_STATE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: STORAGE_BUCKET_STATE
{{- end }}

{{/*
Renders the storage.bucket.workloadOutput value
*/}}
{{- define "airbyte-data-plane.storage.bucket.workloadOutput" }}
    {{- .Values.storage.bucket.workloadOutput | default "airbyte-storage" }}
{{- end }}

{{/*
Renders the storage.bucket.workloadOutput environment variable
*/}}
{{- define "airbyte-data-plane.storage.bucket.workloadOutput.env" }}
- name: STORAGE_BUCKET_WORKLOAD_OUTPUT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: STORAGE_BUCKET_WORKLOAD_OUTPUT
{{- end }}

{{/*
Renders the storage.s3.region value
*/}}
{{- define "airbyte-data-plane.storage.s3.region" }}
    {{- .Values.storage.s3.region }}
{{- end }}

{{/*
Renders the storage.s3.region environment variable
*/}}
{{- define "airbyte-data-plane.storage.s3.region.env" }}
- name: AWS_DEFAULT_REGION
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AWS_DEFAULT_REGION
{{- end }}

{{/*
Renders the storage.s3.authenticationType value
*/}}
{{- define "airbyte-data-plane.storage.s3.authenticationType" }}
    {{- .Values.storage.s3.authenticationType | default "credentials" }}
{{- end }}

{{/*
Renders the storage.s3.authenticationType environment variable
*/}}
{{- define "airbyte-data-plane.storage.s3.authenticationType.env" }}
- name: AWS_AUTHENTICATION_TYPE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: AWS_AUTHENTICATION_TYPE
{{- end }}

{{/*
Renders the storage.s3.accessKeyId value
*/}}
{{- define "airbyte-data-plane.storage.s3.accessKeyId" }}
    {{- .Values.storage.s3.accessKeyId }}
{{- end }}

{{/*
Renders the storage.s3.accessKeyId secret key
*/}}
{{- define "airbyte-data-plane.storage.s3.accessKeyId.secretKey" }}
	{{- .Values.storage.s3.accessKeyIdSecretKey | default "AWS_ACCESS_KEY_ID" }}
{{- end }}

{{/*
Renders the storage.s3.accessKeyId environment variable
*/}}
{{- define "airbyte-data-plane.storage.s3.accessKeyId.env" }}
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.storage.secretName" . }}
      key: {{ include "airbyte-data-plane.storage.s3.accessKeyId.secretKey" . }}
{{- end }}

{{/*
Renders the storage.s3.secretAccessKey value
*/}}
{{- define "airbyte-data-plane.storage.s3.secretAccessKey" }}
    {{- .Values.storage.s3.secretAccessKey }}
{{- end }}

{{/*
Renders the storage.s3.secretAccessKey secret key
*/}}
{{- define "airbyte-data-plane.storage.s3.secretAccessKey.secretKey" }}
	{{- .Values.storage.s3.secretAccessKeySecretKey | default "AWS_SECRET_ACCESS_KEY" }}
{{- end }}

{{/*
Renders the storage.s3.secretAccessKey environment variable
*/}}
{{- define "airbyte-data-plane.storage.s3.secretAccessKey.env" }}
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.storage.secretName" . }}
      key: {{ include "airbyte-data-plane.storage.s3.secretAccessKey.secretKey" . }}
{{- end }}

{{/*
Renders the storage.azure.connectionString value
*/}}
{{- define "airbyte-data-plane.storage.azure.connectionString" }}
    {{- .Values.storage.azure.connectionString }}
{{- end }}

{{/*
Renders the storage.azure.connectionString secret key
*/}}
{{- define "airbyte-data-plane.storage.azure.connectionString.secretKey" }}
	{{- .Values.storage.azure.connectionStringSecretKey | default "AZURE_STORAGE_CONNECTION_STRING" }}
{{- end }}

{{/*
Renders the storage.azure.connectionString environment variable
*/}}
{{- define "airbyte-data-plane.storage.azure.connectionString.env" }}
- name: AZURE_STORAGE_CONNECTION_STRING
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.storage.secretName" . }}
      key: {{ include "airbyte-data-plane.storage.azure.connectionString.secretKey" . }}
{{- end }}

{{/*
Renders the storage.gcs.credentialsJson value
*/}}
{{- define "airbyte-data-plane.storage.gcs.credentialsJson" }}
    {{- .Values.storage.gcs.credentialsJson }}
{{- end }}

{{/*
Renders the storage.gcs.credentialsJson secret key
*/}}
{{- define "airbyte-data-plane.storage.gcs.credentialsJson.secretKey" }}
	{{- .Values.storage.gcs.credentialsJsonSecretKey | default "GOOGLE_APPLICATION_CREDENTIALS_JSON" }}
{{- end }}

{{/*
Renders the storage.gcs.credentialsJson environment variable
*/}}
{{- define "airbyte-data-plane.storage.gcs.credentialsJson.env" }}
- name: GOOGLE_APPLICATION_CREDENTIALS_JSON
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.storage.secretName" . }}
      key: {{ include "airbyte-data-plane.storage.gcs.credentialsJson.secretKey" . }}
{{- end }}

{{/*
Renders the storage.gcs.credentialsJsonPath value
*/}}
{{- define "airbyte-data-plane.storage.gcs.credentialsJsonPath" }}
    {{- .Values.storage.gcs.credentialsJsonPath | default "/secrets/gcp-creds/gcp.json" }}
{{- end }}

{{/*
Renders the storage.gcs.credentialsJsonPath environment variable
*/}}
{{- define "airbyte-data-plane.storage.gcs.credentialsJsonPath.env" }}
- name: GOOGLE_APPLICATION_CREDENTIALS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: GOOGLE_APPLICATION_CREDENTIALS
{{- end }}

{{/*
Renders the storage.minio.accessKeyId value
*/}}
{{- define "airbyte-data-plane.storage.minio.accessKeyId" }}
    {{- .Values.storage.minio.accessKeyId | default "minio" }}
{{- end }}

{{/*
Renders the storage.minio.accessKeyId secret key
*/}}
{{- define "airbyte-data-plane.storage.minio.accessKeyId.secretKey" }}
	{{- .Values.storage.minio.accessKeyIdSecretKey | default "AWS_ACCESS_KEY_ID" }}
{{- end }}

{{/*
Renders the storage.minio.accessKeyId environment variable
*/}}
{{- define "airbyte-data-plane.storage.minio.accessKeyId.env" }}
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.storage.secretName" . }}
      key: {{ include "airbyte-data-plane.storage.minio.accessKeyId.secretKey" . }}
{{- end }}

{{/*
Renders the storage.minio.secretAccessKey value
*/}}
{{- define "airbyte-data-plane.storage.minio.secretAccessKey" }}
    {{- .Values.storage.minio.secretAccessKey | default "minio123" }}
{{- end }}

{{/*
Renders the storage.minio.secretAccessKey secret key
*/}}
{{- define "airbyte-data-plane.storage.minio.secretAccessKey.secretKey" }}
	{{- .Values.storage.minio.secretAccessKeySecretKey | default "AWS_SECRET_ACCESS_KEY" }}
{{- end }}

{{/*
Renders the storage.minio.secretAccessKey environment variable
*/}}
{{- define "airbyte-data-plane.storage.minio.secretAccessKey.env" }}
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.storage.secretName" . }}
      key: {{ include "airbyte-data-plane.storage.minio.secretAccessKey.secretKey" . }}
{{- end }}

{{/*
Renders the storage.minio.endpoint value
*/}}
{{- define "airbyte-data-plane.storage.minio.endpoint" }}
    {{- .Values.storage.minio.endpoint | default (printf "http://airbyte-minio-svc.%s:9000" .Release.Namespace) }}
{{- end }}

{{/*
Renders the storage.minio.endpoint environment variable
*/}}
{{- define "airbyte-data-plane.storage.minio.endpoint.env" }}
- name: MINIO_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MINIO_ENDPOINT
{{- end }}

{{/*
Renders the storage.minio.s3PathStyleAccess value
*/}}
{{- define "airbyte-data-plane.storage.minio.s3PathStyleAccess" }}
	{{- if eq .Values.storage.minio.s3PathStyleAccess nil }}
    	{{- true }}
	{{- else }}
    	{{- .Values.storage.minio.s3PathStyleAccess }}
	{{- end }}
{{- end }}

{{/*
Renders the storage.minio.s3PathStyleAccess environment variable
*/}}
{{- define "airbyte-data-plane.storage.minio.s3PathStyleAccess.env" }}
- name: S3_PATH_STYLE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: S3_PATH_STYLE
{{- end }}

{{/*
Renders the set of all storage environment variables
*/}}
{{- define "airbyte-data-plane.storage.envs" }}
{{- include "airbyte-data-plane.storage.type.env" . }}
{{- include "airbyte-data-plane.storage.bucket.activityPayload.env" . }}
{{- include "airbyte-data-plane.storage.bucket.log.env" . }}
{{- include "airbyte-data-plane.storage.bucket.state.env" . }}
{{- include "airbyte-data-plane.storage.bucket.workloadOutput.env" . }}
{{- $opt := (include "airbyte-data-plane.storage.type" .) }}

{{- if eq $opt "azure" }}
{{- include "airbyte-data-plane.storage.azure.connectionString.env" . }}
{{- end }}

{{- if eq $opt "gcs" }}
{{- include "airbyte-data-plane.storage.gcs.credentialsJson.env" . }}
{{- include "airbyte-data-plane.storage.gcs.credentialsJsonPath.env" . }}
{{- end }}

{{- if eq $opt "minio" }}
{{- include "airbyte-data-plane.storage.minio.accessKeyId.env" . }}
{{- include "airbyte-data-plane.storage.minio.secretAccessKey.env" . }}
{{- include "airbyte-data-plane.storage.minio.endpoint.env" . }}
{{- include "airbyte-data-plane.storage.minio.s3PathStyleAccess.env" . }}
{{- end }}

{{- if eq $opt "s3" }}
{{- include "airbyte-data-plane.storage.s3.region.env" . }}
{{- include "airbyte-data-plane.storage.s3.authenticationType.env" . }}
{{- include "airbyte-data-plane.storage.s3.accessKeyId.env" . }}
{{- include "airbyte-data-plane.storage.s3.secretAccessKey.env" . }}
{{- end }}

{{- end }}

{{/*
Renders the set of all storage config map variables
*/}}
{{- define "airbyte-data-plane.storage.configVars" }}
STORAGE_TYPE: {{ include "airbyte-data-plane.storage.type" . | quote }}
STORAGE_BUCKET_ACTIVITY_PAYLOAD: {{ include "airbyte-data-plane.storage.bucket.activityPayload" . | quote }}
STORAGE_BUCKET_LOG: {{ include "airbyte-data-plane.storage.bucket.log" . | quote }}
STORAGE_BUCKET_STATE: {{ include "airbyte-data-plane.storage.bucket.state" . | quote }}
STORAGE_BUCKET_WORKLOAD_OUTPUT: {{ include "airbyte-data-plane.storage.bucket.workloadOutput" . | quote }}
{{- $opt := (include "airbyte-data-plane.storage.type" .) }}

{{- if eq $opt "azure" }}
{{- end }}

{{- if eq $opt "gcs" }}
GOOGLE_APPLICATION_CREDENTIALS: {{ include "airbyte-data-plane.storage.gcs.credentialsJsonPath" . | quote }}
{{- end }}

{{- if eq $opt "minio" }}
MINIO_ENDPOINT: {{ include "airbyte-data-plane.storage.minio.endpoint" . | quote }}
S3_PATH_STYLE: {{ include "airbyte-data-plane.storage.minio.s3PathStyleAccess" . | quote }}
{{- end }}

{{- if eq $opt "s3" }}
AWS_DEFAULT_REGION: {{ include "airbyte-data-plane.storage.s3.region" . | quote }}
AWS_AUTHENTICATION_TYPE: {{ include "airbyte-data-plane.storage.s3.authenticationType" . | quote }}
{{- end }}

{{- end }}

{{/*
Renders the set of all storage secret variables
*/}}
{{- define "airbyte-data-plane.storage.secrets" }}
{{- $opt := (include "airbyte-data-plane.storage.type" .) }}

{{- if eq $opt "azure" }}
AZURE_STORAGE_CONNECTION_STRING: {{ include "airbyte-data-plane.storage.azure.connectionString" . | quote }}
{{- end }}

{{- if eq $opt "gcs" }}
GOOGLE_APPLICATION_CREDENTIALS_JSON: {{ include "airbyte-data-plane.storage.gcs.credentialsJson" . | quote }}
{{- end }}

{{- if eq $opt "minio" }}
AWS_ACCESS_KEY_ID: {{ include "airbyte-data-plane.storage.minio.accessKeyId" . | quote }}
AWS_SECRET_ACCESS_KEY: {{ include "airbyte-data-plane.storage.minio.secretAccessKey" . | quote }}
{{- end }}

{{- if eq $opt "s3" }}
AWS_ACCESS_KEY_ID: {{ include "airbyte-data-plane.storage.s3.accessKeyId" . | quote }}
AWS_SECRET_ACCESS_KEY: {{ include "airbyte-data-plane.storage.s3.secretAccessKey" . | quote }}
{{- end }}

{{- end }}
