
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Temporal Configuration
*/}}

{{/*
Renders the temporal.host value
*/}}
{{- define "airbyte-data-plane.temporal.host" }}
    {{- ternary (include "airbyte-data-plane.temporal.cloud.host" .) (.Values.temporal.host) (eq (include "airbyte-data-plane.temporal.cloud.enabled" .) "true") }}
{{- end }}

{{/*
Renders the temporal.host environment variable
*/}}
{{- define "airbyte-data-plane.temporal.host.env" }}
- name: TEMPORAL_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_HOST
{{- end }}

{{/*
Renders the temporal.configFilePath value
*/}}
{{- define "airbyte-data-plane.temporal.configFilePath" }}
    {{- .Values.temporal.configFilePath | default "config/dynamicconfig/development.yaml" }}
{{- end }}

{{/*
Renders the temporal.configFilePath environment variable
*/}}
{{- define "airbyte-data-plane.temporal.configFilePath.env" }}
- name: DYNAMIC_CONFIG_FILE_PATH
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: DYNAMIC_CONFIG_FILE_PATH
{{- end }}

{{/*
Renders the temporal.prometheus.endpoint value
*/}}
{{- define "airbyte-data-plane.temporal.prometheus.endpoint" }}
    {{- .Values.temporal.prometheus.endpoint | default "0.0.0.0:9090" }}
{{- end }}

{{/*
Renders the temporal.prometheus.endpoint environment variable
*/}}
{{- define "airbyte-data-plane.temporal.prometheus.endpoint.env" }}
- name: PROMETHEUS_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: PROMETHEUS_ENDPOINT
{{- end }}

{{/*
Renders the set of all temporal environment variables
*/}}
{{- define "airbyte-data-plane.temporal.envs" }}
{{- include "airbyte-data-plane.temporal.host.env" . }}
{{- include "airbyte-data-plane.temporal.configFilePath.env" . }}
{{- include "airbyte-data-plane.temporal.prometheus.endpoint.env" . }}
{{- end }}

{{/*
Renders the set of all temporal config map variables
*/}}
{{- define "airbyte-data-plane.temporal.configVars" }}
TEMPORAL_HOST: {{ include "airbyte-data-plane.temporal.host" . | quote }}
DYNAMIC_CONFIG_FILE_PATH: {{ include "airbyte-data-plane.temporal.configFilePath" . | quote }}
PROMETHEUS_ENDPOINT: {{ include "airbyte-data-plane.temporal.prometheus.endpoint" . | quote }}
{{- end }}

{{/*
Renders the temporal.cloud secret name
*/}}
{{- define "airbyte-data-plane.temporal.cloud.secretName" }}
{{- if .Values.temporal.secretName }}
    {{- .Values.temporal.secretName }}
{{- else }}
    {{- .Values.secretName | default (printf "%s-airbyte-data-plane-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the temporal.cloud.enabled value
*/}}
{{- define "airbyte-data-plane.temporal.cloud.enabled" }}
	{{- if eq .Values.temporal.cloud.enabled nil }}
    	{{- false }}
	{{- else }}
    	{{- .Values.temporal.cloud.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the temporal.cloud.enabled environment variable
*/}}
{{- define "airbyte-data-plane.temporal.cloud.enabled.env" }}
- name: TEMPORAL_CLOUD_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_CLOUD_ENABLED
{{- end }}

{{/*
Renders the temporal.cloud.clientCert value
*/}}
{{- define "airbyte-data-plane.temporal.cloud.clientCert" }}
    {{- .Values.temporal.cloud.clientCert }}
{{- end }}

{{/*
Renders the temporal.cloud.clientCert secret key
*/}}
{{- define "airbyte-data-plane.temporal.cloud.clientCert.secretKey" }}
	{{- .Values.temporal.cloud.clientCertSecretKey | default "TEMPORAL_CLOUD_CLIENT_CERT" }}
{{- end }}

{{/*
Renders the temporal.cloud.clientCert environment variable
*/}}
{{- define "airbyte-data-plane.temporal.cloud.clientCert.env" }}
- name: TEMPORAL_CLOUD_CLIENT_CERT
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.temporal.cloud.secretName" . }}
      key: {{ include "airbyte-data-plane.temporal.cloud.clientCert.secretKey" . }}
{{- end }}

{{/*
Renders the temporal.cloud.clientKey value
*/}}
{{- define "airbyte-data-plane.temporal.cloud.clientKey" }}
    {{- .Values.temporal.cloud.clientKey }}
{{- end }}

{{/*
Renders the temporal.cloud.clientKey secret key
*/}}
{{- define "airbyte-data-plane.temporal.cloud.clientKey.secretKey" }}
	{{- .Values.temporal.cloud.clientKeySecretKey | default "TEMPORAL_CLOUD_CLIENT_KEY" }}
{{- end }}

{{/*
Renders the temporal.cloud.clientKey environment variable
*/}}
{{- define "airbyte-data-plane.temporal.cloud.clientKey.env" }}
- name: TEMPORAL_CLOUD_CLIENT_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-data-plane.temporal.cloud.secretName" . }}
      key: {{ include "airbyte-data-plane.temporal.cloud.clientKey.secretKey" . }}
{{- end }}

{{/*
Renders the temporal.cloud.namespace value
*/}}
{{- define "airbyte-data-plane.temporal.cloud.namespace" }}
    {{- .Values.temporal.cloud.namespace }}
{{- end }}

{{/*
Renders the temporal.cloud.namespace environment variable
*/}}
{{- define "airbyte-data-plane.temporal.cloud.namespace.env" }}
- name: TEMPORAL_CLOUD_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_CLOUD_NAMESPACE
{{- end }}

{{/*
Renders the temporal.cloud.host value
*/}}
{{- define "airbyte-data-plane.temporal.cloud.host" }}
    {{- .Values.temporal.cloud.host }}
{{- end }}

{{/*
Renders the temporal.cloud.host environment variable
*/}}
{{- define "airbyte-data-plane.temporal.cloud.host.env" }}
- name: TEMPORAL_CLOUD_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_CLOUD_HOST
{{- end }}

{{/*
Renders the set of all temporal.cloud environment variables
*/}}
{{- define "airbyte-data-plane.temporal.cloud.envs" }}
{{- include "airbyte-data-plane.temporal.cloud.enabled.env" . }}
{{- include "airbyte-data-plane.temporal.cloud.clientCert.env" . }}
{{- include "airbyte-data-plane.temporal.cloud.clientKey.env" . }}
{{- include "airbyte-data-plane.temporal.cloud.namespace.env" . }}
{{- include "airbyte-data-plane.temporal.cloud.host.env" . }}
{{- end }}

{{/*
Renders the set of all temporal.cloud config map variables
*/}}
{{- define "airbyte-data-plane.temporal.cloud.configVars" }}
TEMPORAL_CLOUD_ENABLED: {{ include "airbyte-data-plane.temporal.cloud.enabled" . | quote }}
TEMPORAL_CLOUD_NAMESPACE: {{ include "airbyte-data-plane.temporal.cloud.namespace" . | quote }}
TEMPORAL_CLOUD_HOST: {{ include "airbyte-data-plane.temporal.cloud.host" . | quote }}
{{- end }}

{{/*
Renders the set of all temporal.cloud secret variables
*/}}
{{- define "airbyte-data-plane.temporal.cloud.secrets" }}
TEMPORAL_CLOUD_CLIENT_CERT: {{ include "airbyte-data-plane.temporal.cloud.clientCert" . | quote }}
TEMPORAL_CLOUD_CLIENT_KEY: {{ include "airbyte-data-plane.temporal.cloud.clientKey" . | quote }}
{{- end }}

{{/*
Renders the temporal.sdk.rpc.timeout value
*/}}
{{- define "airbyte-data-plane.temporal.sdk.rpc.timeout" }}
    {{- .Values.temporal.sdk.rpc.timeout | default "120s" }}
{{- end }}

{{/*
Renders the temporal.sdk.rpc.timeout environment variable
*/}}
{{- define "airbyte-data-plane.temporal.sdk.rpc.timeout.env" }}
- name: TEMPORAL_SDK_RPC_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_SDK_RPC_TIMEOUT
{{- end }}

{{/*
Renders the temporal.sdk.rpc.longPollTimeout value
*/}}
{{- define "airbyte-data-plane.temporal.sdk.rpc.longPollTimeout" }}
    {{- .Values.temporal.sdk.rpc.longPollTimeout | default "140s" }}
{{- end }}

{{/*
Renders the temporal.sdk.rpc.longPollTimeout environment variable
*/}}
{{- define "airbyte-data-plane.temporal.sdk.rpc.longPollTimeout.env" }}
- name: TEMPORAL_SDK_RPC_LONG_POLL_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_SDK_RPC_LONG_POLL_TIMEOUT
{{- end }}

{{/*
Renders the temporal.sdk.rpc.queryTimeout value
*/}}
{{- define "airbyte-data-plane.temporal.sdk.rpc.queryTimeout" }}
    {{- .Values.temporal.sdk.rpc.queryTimeout | default "20s" }}
{{- end }}

{{/*
Renders the temporal.sdk.rpc.queryTimeout environment variable
*/}}
{{- define "airbyte-data-plane.temporal.sdk.rpc.queryTimeout.env" }}
- name: TEMPORAL_SDK_RPC_QUERY_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_SDK_RPC_QUERY_TIMEOUT
{{- end }}

{{/*
Renders the set of all temporal.sdk environment variables
*/}}
{{- define "airbyte-data-plane.temporal.sdk.envs" }}
{{- include "airbyte-data-plane.temporal.sdk.rpc.timeout.env" . }}
{{- include "airbyte-data-plane.temporal.sdk.rpc.longPollTimeout.env" . }}
{{- include "airbyte-data-plane.temporal.sdk.rpc.queryTimeout.env" . }}
{{- end }}

{{/*
Renders the set of all temporal.sdk config map variables
*/}}
{{- define "airbyte-data-plane.temporal.sdk.configVars" }}
TEMPORAL_SDK_RPC_TIMEOUT: {{ include "airbyte-data-plane.temporal.sdk.rpc.timeout" . | quote }}
TEMPORAL_SDK_RPC_LONG_POLL_TIMEOUT: {{ include "airbyte-data-plane.temporal.sdk.rpc.longPollTimeout" . | quote }}
TEMPORAL_SDK_RPC_QUERY_TIMEOUT: {{ include "airbyte-data-plane.temporal.sdk.rpc.queryTimeout" . | quote }}
{{- end }}

{{/*
Renders the temporal.worker.ports value
*/}}
{{- define "airbyte-data-plane.temporal.worker.ports" }}
    {{- join "," (seq 9000 9040) }}
{{- end }}

{{/*
Renders the temporal.worker.ports environment variable
*/}}
{{- define "airbyte-data-plane.temporal.worker.ports.env" }}
- name: TEMPORAL_WORKER_PORTS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: TEMPORAL_WORKER_PORTS
{{- end }}

{{/*
Renders the set of all temporal.worker environment variables
*/}}
{{- define "airbyte-data-plane.temporal.worker.envs" }}
{{- include "airbyte-data-plane.temporal.worker.ports.env" . }}
{{- end }}

{{/*
Renders the set of all temporal.worker config map variables
*/}}
{{- define "airbyte-data-plane.temporal.worker.configVars" }}
TEMPORAL_WORKER_PORTS: {{ include "airbyte-data-plane.temporal.worker.ports" . | quote }}
{{- end }}
