
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Worker Configuration
*/}}

{{/*
Renders the worker.activityMaxAttempt value
*/}}
{{- define "airbyte-data-plane.worker.activityMaxAttempt" }}
    {{- .Values.worker.activityMaxAttempt }}
{{- end }}

{{/*
Renders the worker.activityMaxAttempt environment variable
*/}}
{{- define "airbyte-data-plane.worker.activityMaxAttempt.env" }}
- name: ACTIVITY_MAX_ATTEMPT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: ACTIVITY_MAX_ATTEMPT
{{- end }}

{{/*
Renders the worker.activityInitialDelayBetweenAttemptsSeconds value
*/}}
{{- define "airbyte-data-plane.worker.activityInitialDelayBetweenAttemptsSeconds" }}
    {{- .Values.worker.activityInitialDelayBetweenAttemptsSeconds }}
{{- end }}

{{/*
Renders the worker.activityInitialDelayBetweenAttemptsSeconds environment variable
*/}}
{{- define "airbyte-data-plane.worker.activityInitialDelayBetweenAttemptsSeconds.env" }}
- name: ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS
{{- end }}

{{/*
Renders the worker.activityMaxDelayBetweenAttemptsSeconds value
*/}}
{{- define "airbyte-data-plane.worker.activityMaxDelayBetweenAttemptsSeconds" }}
    {{- .Values.worker.activityMaxDelayBetweenAttemptsSeconds }}
{{- end }}

{{/*
Renders the worker.activityMaxDelayBetweenAttemptsSeconds environment variable
*/}}
{{- define "airbyte-data-plane.worker.activityMaxDelayBetweenAttemptsSeconds.env" }}
- name: ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS
{{- end }}

{{/*
Renders the worker.configRoot value
*/}}
{{- define "airbyte-data-plane.worker.configRoot" }}
    {{- .Values.worker.configRoot | default "/configs" }}
{{- end }}

{{/*
Renders the worker.configRoot environment variable
*/}}
{{- define "airbyte-data-plane.worker.configRoot.env" }}
- name: CONFIG_ROOT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: CONFIG_ROOT
{{- end }}

{{/*
Renders the worker.maxNotifyWorkers value
*/}}
{{- define "airbyte-data-plane.worker.maxNotifyWorkers" }}
    {{- .Values.worker.maxNotifyWorkers | default 30 }}
{{- end }}

{{/*
Renders the worker.maxNotifyWorkers environment variable
*/}}
{{- define "airbyte-data-plane.worker.maxNotifyWorkers.env" }}
- name: MAX_NOTIFY_WORKERS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MAX_NOTIFY_WORKERS
{{- end }}

{{/*
Renders the worker.maxSyncWorkers value
*/}}
{{- define "airbyte-data-plane.worker.maxSyncWorkers" }}
    {{- .Values.worker.maxSyncWorkers | default 5 }}
{{- end }}

{{/*
Renders the worker.maxSyncWorkers environment variable
*/}}
{{- define "airbyte-data-plane.worker.maxSyncWorkers.env" }}
- name: MAX_SYNC_WORKERS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: MAX_SYNC_WORKERS
{{- end }}

{{/*
Renders the worker.syncJobMaxAttempts value
*/}}
{{- define "airbyte-data-plane.worker.syncJobMaxAttempts" }}
    {{- .Values.worker.syncJobMaxAttempts | default 3 }}
{{- end }}

{{/*
Renders the worker.syncJobMaxAttempts environment variable
*/}}
{{- define "airbyte-data-plane.worker.syncJobMaxAttempts.env" }}
- name: SYNC_JOB_MAX_ATTEMPTS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: SYNC_JOB_MAX_ATTEMPTS
{{- end }}

{{/*
Renders the worker.syncJobMaxTimeoutDays value
*/}}
{{- define "airbyte-data-plane.worker.syncJobMaxTimeoutDays" }}
    {{- .Values.worker.syncJobMaxTimeoutDays | default 3 }}
{{- end }}

{{/*
Renders the worker.syncJobMaxTimeoutDays environment variable
*/}}
{{- define "airbyte-data-plane.worker.syncJobMaxTimeoutDays.env" }}
- name: SYNC_JOB_MAX_TIMEOUT_DAYS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: SYNC_JOB_MAX_TIMEOUT_DAYS
{{- end }}

{{/*
Renders the worker.syncJobInitRetryTimeoutMinutes value
*/}}
{{- define "airbyte-data-plane.worker.syncJobInitRetryTimeoutMinutes" }}
    {{- .Values.worker.syncJobInitRetryTimeoutMinutes | default 5 }}
{{- end }}

{{/*
Renders the worker.syncJobInitRetryTimeoutMinutes environment variable
*/}}
{{- define "airbyte-data-plane.worker.syncJobInitRetryTimeoutMinutes.env" }}
- name: SYNC_JOB_INIT_RETRY_TIMEOUT_MINUTES
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: SYNC_JOB_INIT_RETRY_TIMEOUT_MINUTES
{{- end }}

{{/*
Renders the worker.useStreamCapableState value
*/}}
{{- define "airbyte-data-plane.worker.useStreamCapableState" }}
	{{- if eq .Values.worker.useStreamCapableState nil }}
    	{{- true }}
	{{- else }}
    	{{- .Values.worker.useStreamCapableState }}
	{{- end }}
{{- end }}

{{/*
Renders the worker.useStreamCapableState environment variable
*/}}
{{- define "airbyte-data-plane.worker.useStreamCapableState.env" }}
- name: USE_STREAM_CAPABLE_STATE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: USE_STREAM_CAPABLE_STATE
{{- end }}

{{/*
Renders the worker.workflowFailureRestartDelaySeconds value
*/}}
{{- define "airbyte-data-plane.worker.workflowFailureRestartDelaySeconds" }}
    {{- .Values.worker.workflowFailureRestartDelaySeconds }}
{{- end }}

{{/*
Renders the worker.workflowFailureRestartDelaySeconds environment variable
*/}}
{{- define "airbyte-data-plane.worker.workflowFailureRestartDelaySeconds.env" }}
- name: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
{{- end }}

{{/*
Renders the worker.workspaceDockerMount value
*/}}
{{- define "airbyte-data-plane.worker.workspaceDockerMount" }}
    {{- .Values.worker.workspaceDockerMount | default "airbyte_workspace" }}
{{- end }}

{{/*
Renders the worker.workspaceDockerMount environment variable
*/}}
{{- define "airbyte-data-plane.worker.workspaceDockerMount.env" }}
- name: WORKSPACE_DOCKER_MOUNT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: WORKSPACE_DOCKER_MOUNT
{{- end }}

{{/*
Renders the worker.workspaceRoot value
*/}}
{{- define "airbyte-data-plane.worker.workspaceRoot" }}
    {{- .Values.worker.workspaceRoot | default "/workspace" }}
{{- end }}

{{/*
Renders the worker.workspaceRoot environment variable
*/}}
{{- define "airbyte-data-plane.worker.workspaceRoot.env" }}
- name: WORKSPACE_ROOT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: WORKSPACE_ROOT
{{- end }}

{{/*
Renders the worker.environment value
*/}}
{{- define "airbyte-data-plane.worker.environment" }}
    {{- "kubernetes" }}
{{- end }}

{{/*
Renders the worker.environment environment variable
*/}}
{{- define "airbyte-data-plane.worker.environment.env" }}
- name: WORKER_ENVIRONMENT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: WORKER_ENVIRONMENT
{{- end }}

{{/*
Renders the set of all worker environment variables
*/}}
{{- define "airbyte-data-plane.worker.envs" }}
{{- include "airbyte-data-plane.worker.activityMaxAttempt.env" . }}
{{- include "airbyte-data-plane.worker.activityInitialDelayBetweenAttemptsSeconds.env" . }}
{{- include "airbyte-data-plane.worker.activityMaxDelayBetweenAttemptsSeconds.env" . }}
{{- include "airbyte-data-plane.worker.configRoot.env" . }}
{{- include "airbyte-data-plane.worker.maxNotifyWorkers.env" . }}
{{- include "airbyte-data-plane.worker.maxSyncWorkers.env" . }}
{{- include "airbyte-data-plane.worker.syncJobMaxAttempts.env" . }}
{{- include "airbyte-data-plane.worker.syncJobMaxTimeoutDays.env" . }}
{{- include "airbyte-data-plane.worker.syncJobInitRetryTimeoutMinutes.env" . }}
{{- include "airbyte-data-plane.worker.useStreamCapableState.env" . }}
{{- include "airbyte-data-plane.worker.workflowFailureRestartDelaySeconds.env" . }}
{{- include "airbyte-data-plane.worker.workspaceDockerMount.env" . }}
{{- include "airbyte-data-plane.worker.workspaceRoot.env" . }}
{{- include "airbyte-data-plane.worker.environment.env" . }}
{{- end }}

{{/*
Renders the set of all worker config map variables
*/}}
{{- define "airbyte-data-plane.worker.configVars" }}
ACTIVITY_MAX_ATTEMPT: {{ include "airbyte-data-plane.worker.activityMaxAttempt" . | quote }}
ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS: {{ include "airbyte-data-plane.worker.activityInitialDelayBetweenAttemptsSeconds" . | quote }}
ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS: {{ include "airbyte-data-plane.worker.activityMaxDelayBetweenAttemptsSeconds" . | quote }}
CONFIG_ROOT: {{ include "airbyte-data-plane.worker.configRoot" . | quote }}
MAX_NOTIFY_WORKERS: {{ include "airbyte-data-plane.worker.maxNotifyWorkers" . | quote }}
MAX_SYNC_WORKERS: {{ include "airbyte-data-plane.worker.maxSyncWorkers" . | quote }}
SYNC_JOB_MAX_ATTEMPTS: {{ include "airbyte-data-plane.worker.syncJobMaxAttempts" . | quote }}
SYNC_JOB_MAX_TIMEOUT_DAYS: {{ include "airbyte-data-plane.worker.syncJobMaxTimeoutDays" . | quote }}
SYNC_JOB_INIT_RETRY_TIMEOUT_MINUTES: {{ include "airbyte-data-plane.worker.syncJobInitRetryTimeoutMinutes" . | quote }}
USE_STREAM_CAPABLE_STATE: {{ include "airbyte-data-plane.worker.useStreamCapableState" . | quote }}
WORKFLOW_FAILURE_RESTART_DELAY_SECONDS: {{ include "airbyte-data-plane.worker.workflowFailureRestartDelaySeconds" . | quote }}
WORKSPACE_DOCKER_MOUNT: {{ include "airbyte-data-plane.worker.workspaceDockerMount" . | quote }}
WORKSPACE_ROOT: {{ include "airbyte-data-plane.worker.workspaceRoot" . | quote }}
WORKER_ENVIRONMENT: {{ include "airbyte-data-plane.worker.environment" . | quote }}
{{- end }}
