
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Workloadapiserver Configuration
*/}}

{{/*
Renders the workloadApiServer.host value
*/}}
{{- define "airbyte-data-plane.workloadApiServer.host" }}
    {{- .Values.workloadApiServer.host | default (include "airbyte-data-plane.common.airbyteUrl" .) }}
{{- end }}

{{/*
Renders the workloadApiServer.host environment variable
*/}}
{{- define "airbyte-data-plane.workloadApiServer.host.env" }}
- name: WORKLOAD_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-data-plane-env
      key: WORKLOAD_API_HOST
{{- end }}

{{/*
Renders the set of all workloadApiServer environment variables
*/}}
{{- define "airbyte-data-plane.workloadApiServer.envs" }}
{{- include "airbyte-data-plane.workloadApiServer.host.env" . }}
{{- end }}

{{/*
Renders the set of all workloadApiServer config map variables
*/}}
{{- define "airbyte-data-plane.workloadApiServer.configVars" }}
WORKLOAD_API_HOST: {{ include "airbyte-data-plane.workloadApiServer.host" . | quote }}
{{- end }}
