{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: airbyte-db-svc
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  labels:
    {{ include "airbyte.databaseLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    {{ include "airbyte.databaseSelectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airbyte-db
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  labels:
    {{ include "airbyte.databaseLabels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: airbyte-db-svc
  selector:
    matchLabels:
      {{ include "airbyte.databaseSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "airbyte.databaseSelectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
          {{- printf "- name: %s" .name | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: airbyte-db-container
          image: {{ include "imageUrl" (list .Values.postgresql.image $) }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          securityContext: {{- toYaml .Values.postgresql.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: airbyte-volume-db
              mountPath: /var/lib/postgresql/data
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.postgresql.podSecurityContext | nindent 8 }}

  volumeClaimTemplates:
  - metadata:
      name: airbyte-volume-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
{{- end }}
