{{- if and (eq .Values.global.deploymentMode "oss") (eq (lower (default "" .Values.global.storage.type)) "gcs") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcs-log-creds
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
type: Opaque
data:
  gcp.json: "{{ .Values.global.storage.gcs.credentialsJson }}"
{{- end }}
