{{- if and (eq .Values.global.deploymentMode "oss") (eq .Values.global.edition "pro") }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
      {{- if .Values.extraLabels }}
      {{ toYaml (mergeOverwrite .Values.extraLabels .Values.global.extraLabels) | nindent 4 }}
      {{- end }}
      {{- if .Values.podLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 4 }}
      {{- end }}
spec:
  serviceAccountName: {{ .Values.global.serviceAccountName }}
  {{- if .Values.global.imagePullSecrets }}
  imagePullSecrets:
    {{- range .Values.global.imagePullSecrets }}
      {{- printf "- name: %s" .name | nindent 2 }}
      {{- end }}
  {{- end }}
  restartPolicy: Never
  {{- if .Values.nodeSelector }}
  nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
  {{- end }}
  {{- if .Values.affinity }}
  affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
  {{- end }}
  initContainers:
    - name: keycloak-readiness-check
      image: curlimages/curl:8.1.1
      command: [ "sh", "-c", "until curl --output /dev/null --head --fail http://${KEYCLOAK_INTERNAL_HOST}/auth/health/ready; do sleep 1; done;" ]
      env:
        - name: KEYCLOAK_INTERNAL_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName | default (printf "%s-airbyte-env" .Release.Name) }}
              key: KEYCLOAK_INTERNAL_HOST
  {{- if .Values.extraInitContainers }}
  {{- toYaml .Values.extraInitContainers | nindent 4 }}
  {{- end }}
  containers:
    - name: airbyte-keycloak-setup-container
      image: {{ printf "%s:%s" .Values.image.repository (include "keycloak-setup.imageTag" .) }}
      imagePullPolicy: "{{ .Values.image.pullPolicy }}"
      env:
        - name: KEYCLOAK_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
              key: KEYCLOAK_ADMIN_USER
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KEYCLOAK_INTERNAL_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName | default (printf "%s-airbyte-env" .Release.Name) }}
              key: KEYCLOAK_INTERNAL_HOST
        - name: KEYCLOAK_SETUP_RESET_REALM
          value: {{ .Values.resetRealm | default "false" | quote }}
        # Values from secret
        {{- if .Values.secrets }}
        {{- range $k, $v := .Values.secrets }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: {{ $k }}
        {{- end }}
        {{- end }}

        # Values from env
        {{- if .Values.env_vars }}
        {{- range $k, $v := mergeOverwrite .Values.env_vars .Values.global.env_vars }}
        - name: {{ $k }}
          value: {{ $v | quote }}
        {{- end }}
        {{- end }}

        # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
        {{- if .Values.extraEnv }}
        {{- toYaml .Values.extraEnv | nindent 8 }}
        {{- end }}

      {{- if .Values.resources }}
      resources: {{- toYaml .Values.resources | nindent 8 }}
      {{- end }}
      volumeMounts:
        - name: airbyte-yml-volume
          mountPath: /app/configs/airbyte.yml
          subPath: fileContents
      {{- if .Values.extraVolumeMounts }}
      {{- toYaml .Values.extraVolumeMounts | nindent 8 }}
      {{- end }}
      {{- if .Values.containerSecurityContext }}
      securityContext: {{- toYaml .Values.containerSecurityContext | nindent 8 }}
      {{- end }}
    {{- if .Values.extraContainers }}
    {{ toYaml .Values.extraContainers | nindent 4 }}
    {{- end }}
    {{- if .Values.global.extraContainers }}
    {{ toYaml .Values.global.extraContainers | nindent 4 }}
    {{- end }}
  volumes:
    - name: airbyte-yml-volume
      configMap:
        name: {{ .Release.Name }}-airbyte-yml
  {{- if .Values.extraVolumes }}
  {{- toYaml .Values.extraVolumes | nindent 4 }}
  {{- end }}
  {{- end }}