/*
 * Copyright (c) 2020-2025 Airbyte, Inc., all rights reserved.
 */

package io.airbyte.config

enum class ConfigNotFoundType {
  ACTOR_CATALOG,
  ACTOR_DEFINITION_VERSION,
  CONNECTOR_BUILDER_PROJECT,
  DATAPLANE_GROUP,
  DECLARATIVE_MANIFEST,
  DESTINATION_CONNECTION,
  DESTINATION_OAUTH_PARAM,
  ORGANIZATION,
  PERMISSION,
  SCOPED_CONFIGURATION,
  SECRET_PERSISTENCE_CONFIG,
  SOURCE_CONNECTION,
  SOURCE_OAUTH_PARAM,
  STANDARD_DESTINATION_DEFINITION,
  STANDARD_SOURCE_DEFINITION,
  STANDARD_SYNC,
  STANDARD_SYNC_OPERATION,
  STANDARD_WORKSPACE,
  TAG,
  USER,
  USER_INVITATION,
  WORKSPACE_SERVICE_ACCOUNT,
}
