{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airbyte-data-plane.serviceAccountName" . }}
  labels:
    {{- include "airbyte-data-plane.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "airbyte-data-plane.serviceAccountName" . }}-role
  labels:
    {{- include "airbyte-data-plane.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["jobs", "pods", "pods/log", "pods/exec", "pods/attach", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # over-permission for now
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airbyte-data-plane.serviceAccountName" . }}-binding
  labels:
    {{- include "airbyte-data-plane.labels" . | nindent 4 }}
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ include "airbyte-data-plane.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "airbyte-data-plane.serviceAccountName" . }}
{{- end }}
