name: "Cache Build Artifacts"
description: "Cache Java, Javascript and Python build artifacts to reduce build time"
inputs:
  cache-key:
    description: "Key to use for caching"
    required: true
  cache-python:
    description: "Whether to cache Python dependencies. Only relevant if building connector modules. true or false"
    default: "true"
    required: true

runs:
  using: "composite"
  steps:
    - name: Pip Caching
      if: ${{ inputs.cache_python }} == 'true'
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/pip
        key: ${{ inputs.cache-key }}-pip-${{ runner.os }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ inputs.cache-key }}-pip-${{ runner.os }}-

    - name: Npm Caching
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.npm
        key: ${{ inputs.cache-key }}-npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ inputs.cache-key }}-npm-${{ runner.os }}-

    - name: pnpm Caching
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.local/share/pnpm/store
          ~/.cache/Cypress
        key: ${{ inputs.cache-key }}-pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ inputs.cache-key }}-pnpm-${{ runner.os }}-

    # gradle caching is handled by the gradle/actions/setup-gradle action
    # see https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#incompatibility-with-other-caching-mechanisms
    - name: Python Caching
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          **/.venv
        key: ${{ inputs.cache-key }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
