micronaut:
  metrics:
    enabled: false
  server:
    port: -1 # Random port for tests

airbyte:
  secret:
    persistence: TESTING_CONFIG_DB_TABLE

datasources:
  local-secrets:
    url: jdbc:h2:mem:default
    driverClassName: org.h2.Driver
    username: sa
    password: ""

endpoints:
  all:
    port: -1 # Random port for tests

jooq:
  datasources:
    local-secrets:
      jackson-converter-enabled: true
      sql-dialect: H2
