micrometer:
  metrics:
    enabled: false

airbyte:
  secret:
    persistence: TESTING_CONFIG_DB_TABLE

datasources:
  local-secrets:
    connection-test-query: SELECT 1
    connection-timeout: 30000
    idle-timeout: 600000
    initialization-fail-timeout: -1 # Disable fail fast checking to avoid issues due to other pods not being started in time
    maximum-pool-size: 20
    minimum-idle: 0
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    pool-name: config-pool

jooq:
  datasources:
    local-secrets:
      jackson-converter-enabled: true
      sql-dialect: POSTGRES
