---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/ConnectorBuilderProject.yaml
title: ActorDefinitionConfigInjection
description: JSON object that is injected into the config for every run of the referenced actor definition
type: object
required:
  - actorDefinitionId
  - jsonToInject
  - injectionPath
additionalProperties: false
properties:
  injectionPath:
    description: Name of the property of the root object of the configuration to inject into. Does not support deep paths via dot notation.
    type: string
  actorDefinitionId:
    type: string
    format: uuid
  jsonToInject:
    description: Integration specific blob. Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
