---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/Application.yaml
title: Application
description: An Application for a user or non-user entity i.e. an organization
type: object
required:
  - name
additionalProperties: false
properties:
  id:
    type: string
    description: An ID that uniquely identifies the Application in the downstream service. Is used for deletion.
  name:
    description: Caption name for the Application
    type: string
  client_id:
    description: The client id, only returned on creation
    type: string
  client_secret:
    description: The client secret, only returned on creation
    type: string
  createdOn:
    type: string
    description: A date string in ISO 8601 format (e.g. 2021-01-01T00:00:00Z) that the key was created.
    format: string
