---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/AwsAccessKeySecretPersistenceConfig.yaml
title: AwsAccessKeySecretPersistenceConfig
description: AWS SecretPersistenceConfig to be passed into the RuntimeSecretPersistence class.
type: object
additionalProperties: true
properties:
  awsAccessKey:
    description: AWS access key
    type: string
  awsSecretAccessKey:
    description: AWS secret access key
    type: string
  awsRegion:
    description: AWS region
    type: string
