---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/AwsRoleSecretPersistenceConfig.yaml
title: AwsRoleSecretPersistenceConfig
description: AWS SecretPersistenceConfig to be passed into the RuntimeSecretPersistence class.
type: object
additionalProperties: true
properties:
  roleArn:
    description: AWS role ARN to assume
    type: string
  awsRegion:
    description: AWS region
    type: string
  externalId:
    description: AWS external ID
    type: string
  tagKey:
    description: Tag key to set on secret write
    type: string
  kmsKeyArn:
    description: KMS Key ARN to use for encryption of secrets
    type: string
