---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/AwsSecretPersistenceConfig.yaml
title: AwsSecretPersistenceConfig
description: AWS SecretPersistenceConfig to be passed into the RuntimeSecretPersistence class.
type: object
additionalProperties: true
properties:
  auth_type:
    enum:
      - AWS_ACCESS_KEY
      - AWS_ROLE
  data:
    oneOf:
      - $ref: AwsAccessKeySecretPersistenceConfig.yaml
      - $ref: AwsRoleSecretPersistenceConfig.yaml
