---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/JobCheckConnectionConfig.yaml
title: JobCheckConnectionConfig
description: job check connection config
type: object
additionalProperties: true
required:
  - connectionConfiguration
  - dockerImage
properties:
  actorType:
    "$ref": ActorType.yaml
  actorId:
    description: The ID of the actor being checked, so we can persist config updates
    type: string
    format: uuid
  connectionConfiguration:
    description: Integration specific configuration.
    type: object
    existingJavaType: io.airbyte.config.secrets.ConfigWithSecretReferences
  dockerImage:
    type: string
  protocolVersion:
    type: object
    existingJavaType: io.airbyte.commons.version.Version
  isCustomConnector:
    description: determine if the running image is a custom connector.
    type: boolean
  resourceRequirements:
    description: optional resource requirements to run check workers; will use bigger one of this value or the default check worker resource requirements.
    type: object
    "$ref": ResourceRequirements.yaml
