---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/JobSyncConfig.yaml
title: JobSyncConfig
description: job sync config
type: object
additionalProperties: true
required:
  - configuredAirbyteCatalog
  - sourceDockerImage
  - destinationDockerImage
properties:
  namespaceDefinition:
    "$ref": NamespaceDefinitionType.yaml
  namespaceFormat:
    type: string
    default: null
    example: "${SOURCE_NAMESPACE}"
  prefix:
    description: Prefix that will be prepended to the name of each stream when it is written to the destination.
    type: string
  configuredAirbyteCatalog:
    description: the configured airbyte catalog
    type: object
    existingJavaType: io.airbyte.protocol.models.ConfiguredAirbyteCatalog
  sourceDockerImage:
    description: Image name of the source with tag.
    type: string
  sourceProtocolVersion:
    description: Airbyte Protocol Version of the source
    type: object
    existingJavaType: io.airbyte.commons.version.Version
  destinationDockerImage:
    description: Image name of the destination with tag.
    type: string
  destinationProtocolVersion:
    description: Airbyte Protocol Version of the destination
    type: object
    existingJavaType: io.airbyte.commons.version.Version
  operationSequence:
    description: Sequence of configurations of operations to apply as part of the sync
    type: array
    items:
      "$ref": StandardSyncOperation.yaml
  webhookOperationConfigs:
    description: The webhook operation configs belonging to this workspace. Must conform to WebhookOperationConfigs.yaml.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  syncResourceRequirements:
    description: Resource requirements to use for the sync
    $ref: SyncResourceRequirements.yaml
  isSourceCustomConnector:
    description: determine if the source running image is a custom connector.
    type: boolean
  isDestinationCustomConnector:
    description: determine if the destination running image is a custom connector.
    type: boolean
  workspaceId:
    description: The id of the workspace associated with the sync
    type: string
    format: uuid
  sourceDefinitionVersionId:
    description: The id of the source definition version used for the sync
    type: string
    format: uuid
  destinationDefinitionVersionId:
    description: The id of the destination definition version used for the sync
    type: string
    format: uuid
