---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/JobSyncConfig.yaml
title: JobSyncConfig
description: job sync config
type: object
additionalProperties: true
properties:
  operationSequence:
    description: Sequence of configurations of operations to apply as part of the sync
    type: array
    items:
      "$ref": StandardSyncOperation.yaml
  webhookOperationConfigs:
    description: The webhook operation configs belonging to this workspace. Must conform to WebhookOperationConfigs.yaml.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
