---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/OrganizationPaymentConfig.yaml
title: OrganizationPaymentConfig
description: Organization Payment Config
type: object
required:
  - organizationId
  - payment_status
  - created_at
  - updated_at
additionalProperties: true
properties:
  organizationId:
    description: ID of the associated organization
    type: string
    format: uuid
  payment_provider_id:
    description: ID of the external payment provider (ex. a Stripe Customer ID)
    type: string
  payment_status:
    description: Payment status for the organization
    $ref: PaymentStatus.yaml
  grace_period_end_at:
    description: If set, the date at which the organization's grace period ends and syncs will be disabled
    type: integer
    format: int64
  usage_category_override:
    description: If set, the usage category that the organization should always be billed with
    $ref: UsageCategoryOverride.yaml
  created_at:
    description: Creation timestamp of the organization payment config
    type: integer
    format: int64
  updated_at:
    description: Last updated timestamp of the organization payment config
    type: integer
    format: int64
