---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/SecretPersistenceConfig.yaml
title: SecretPersistenceConfig
description: A configuration object used to instantiate a SecretPersistence object at runtime
type: object
required:
  - scopeId
  - scopeType
  - secretPersistenceType
  - configuration
properties:
  secretPersistenceType:
    "$ref": SecretPersistenceType.yaml
  configuration:
    description: The value from the secret coordinate in the global secret persistence that contains the override secret persistence config
    type: object
    existingJavaType: java.util.Map<String, String>
  scopeId:
    description: The resource ID tied to this secret persistence configuration.
    type: string
    format: uuid
  scopeType:
    $ref: ScopeType.yaml
