---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/SecretPersistenceConfig.yaml
title: SecretPersistenceConfig
description: A configuration object used to instantiate a SecretPersistence object at runtime
type: object
required:
  - secretPersistenceType
  - configuration
properties:
  secretPersistenceType:
    "$ref": SecretPersistenceType.yaml
  configuration:
    description: The configuration to use to create the SecretPersistence object. The data here depends on what type of Persistence object is being created.
    type: object
    existingJavaType: java.util.HashMap<String, String>
  scopeId:
    description: The resource ID tied to this secret persistence configuration.
    type: string
    format: uuid
  scopeType:
    $ref: ResourceScope.yaml
