---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/SourceActorConfig.yaml
title: SourceActorConfig
description: Subset of the shared properties for the actor config.
type: object
additionalProperties: true
properties:
  use_file_transfer:
    type: boolean
    default: false
