## This file configures authentication for the Community edition of Airbyte. It is loaded by the
# EditionPropertySourceLoader when AIRBYTE_EDITION is set to "community".
micronaut:
  security:
    enabled: ${API_AUTHORIZATION_ENABLED:false}
    endpoints:
      login:
        enabled: true
        path: /api/login
      logout:
        enabled: true
        path: /api/logout
      oauth:
        path: /api/oauth/access_token
    authentication: cookie
    redirect:
      enabled: false
    token:
      cookie:
        enabled: true
        ## TODO: don't do same-site: None on actual deploys (only local dev). We also might need to turn off cookie-secure for http only installs
        ## solution 1: additional application.yml for cookie-same-site and cookie-secure for local dev?
        ## solution 2: use a env variable and set it to None for local dev
        cookie-same-site: None
        cookie-secure: true
      refresh:
        cookie:
          enabled: true
          cookie-same-site: None
          cookie-secure: true
          cookie-max-age: PT5M
      generator:
        access-token:
          ## Warning: if this is ever exposed to users to customize, the frontend will need to be updated
          expiration: 180 # 3  mins
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${AB_JWT_SIGNATURE_SECRET:51c5739d-1145-4076-b190-8904d2c5de06}
        generator:
          refresh-token:
            enabled: true
            secret: ${AB_JWT_SIGNATURE_SECRET:51c5739d-1145-4076-b190-8904d2c5de06}

airbyte:
  edition: community
  auth:
    instanceAdmin:
      username: ${AB_INSTANCE_ADMIN:airbyte}
      password: ${AB_INSTANCE_ADMIN_PASSWORD:password}
      clientId: ${AB_INSTANCE_ADMIN_CLIENT_ID:00000000-00000000-00000000-00000000}
      clientSecret: ${AB_INSTANCE_ADMIN_CLIENT_SECRET:5ba6a164-4a0b-4efa-8317-83b82648b16b}
