micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: /api/login
      logout:
        enabled: true
        path: /api/logout
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${AB_JWT_SIGNATURE_SECRET:51c5739d-1145-4076-b190-8904d2c5de06}
        generator:
          refresh-token:
            enabled: true
            secret: ${AB_JWT_REFRESH_TOKEN_SECRET:d9f2755b-bd7c-49af-89d3-757de41f045a}
    authentication: bearer

airbyte:
  auth:
    instanceAdmin:
      username: ${AB_INSTANCE_ADMIN:airbyte}
      password: ${AB_INSTANCE_ADMIN_PASSWORD:password}
      clientId: ${AB_INSTANCE_ADMIN_CLIENT_ID:00000000-00000000-00000000-00000000}
      clientSecret: ${AB_INSTANCE_ADMIN_CLIENT_SECRET:5ba6a164-4a0b-4efa-8317-83b82648b16b}
