
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Aws Configuration
*/}}

{{/*
Renders the aws secret name
*/}}
{{- define "airbyte.aws.secretName" }}
{{- if .Values.global.aws.secretName }}
    {{- .Values.global.aws.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the global.aws.assumeRole.accessKeyId value
*/}}
{{- define "airbyte.aws.assumeRole.accessKeyId" }}
    {{- .Values.global.aws.assumeRole.accessKeyId }}
{{- end }}

{{/*
Renders the aws.assumeRole.accessKeyId secret key
*/}}
{{- define "airbyte.aws.assumeRole.accessKeyId.secretKey" }}
	{{- .Values.global.aws.assumeRole.accessKeyIdSecretKey | default "AWS_ASSUME_ROLE_ACCESS_KEY_ID" }}
{{- end }}

{{/*
Renders the aws.assumeRole.accessKeyId environment variable
*/}}
{{- define "airbyte.aws.assumeRole.accessKeyId.env" }}
- name: AWS_ASSUME_ROLE_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.aws.secretName" . }}
      key: {{ include "airbyte.aws.assumeRole.accessKeyId.secretKey" . }}
{{- end }}

{{/*
Renders the global.aws.assumeRole.secretAccessKey value
*/}}
{{- define "airbyte.aws.assumeRole.secretAccessKey" }}
    {{- .Values.global.aws.assumeRole.secretAccessKey }}
{{- end }}

{{/*
Renders the aws.assumeRole.secretAccessKey secret key
*/}}
{{- define "airbyte.aws.assumeRole.secretAccessKey.secretKey" }}
	{{- .Values.global.aws.assumeRole.secretAccessKeySecretKey | default "AWS_ASSUME_ROLE_SECRET_ACCESS_KEY" }}
{{- end }}

{{/*
Renders the aws.assumeRole.secretAccessKey environment variable
*/}}
{{- define "airbyte.aws.assumeRole.secretAccessKey.env" }}
- name: AWS_ASSUME_ROLE_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.aws.secretName" . }}
      key: {{ include "airbyte.aws.assumeRole.secretAccessKey.secretKey" . }}
{{- end }}

{{/*
Renders the global.aws.assumeRole.secretName value
*/}}
{{- define "airbyte.aws.assumeRole.secretName" }}
    {{- .Values.global.aws.assumeRole.secretName | default (include "airbyte.aws.secretName" .) }}
{{- end }}

{{/*
Renders the aws.assumeRole.secretName environment variable
*/}}
{{- define "airbyte.aws.assumeRole.secretName.env" }}
- name: AWS_ASSUME_ROLE_SECRET_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AWS_ASSUME_ROLE_SECRET_NAME
{{- end }}

{{/*
Renders the set of all aws environment variables
*/}}
{{- define "airbyte.aws.envs" }}
{{- include "airbyte.aws.assumeRole.accessKeyId.env" . }}
{{- include "airbyte.aws.assumeRole.secretAccessKey.env" . }}
{{- include "airbyte.aws.assumeRole.secretName.env" . }}
{{- end }}

{{/*
Renders the set of all aws config map variables
*/}}
{{- define "airbyte.aws.configVars" }}
AWS_ASSUME_ROLE_SECRET_NAME: {{ include "airbyte.aws.assumeRole.secretName" . | quote }}
{{- end }}

{{/*
Renders the set of all aws secret variables
*/}}
{{- define "airbyte.aws.secrets" }}
AWS_ASSUME_ROLE_ACCESS_KEY_ID: {{ include "airbyte.aws.assumeRole.accessKeyId" . | quote }}
AWS_ASSUME_ROLE_SECRET_ACCESS_KEY: {{ include "airbyte.aws.assumeRole.secretAccessKey" . | quote }}
{{- end }}
