
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Common Configuration
*/}}

{{/*
Renders the common secret name
*/}}
{{- define "airbyte.common.secretName" }}
{{- if .Values.global.secretName }}
    {{- .Values.global.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the global.edition value
*/}}
{{- define "airbyte.common.edition" }}
    {{- .Values.global.edition | default "community" }}
{{- end }}

{{/*
Renders the common.edition environment variable
*/}}
{{- define "airbyte.common.edition.env" }}
- name: AIRBYTE_EDITION
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_EDITION
{{- end }}

{{/*
Renders the global.version value
*/}}
{{- define "airbyte.common.version" }}
    {{- .Values.global.version | default .Chart.AppVersion }}
{{- end }}

{{/*
Renders the common.version environment variable
*/}}
{{- define "airbyte.common.version.env" }}
- name: AIRBYTE_VERSION
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_VERSION
{{- end }}

{{/*
Renders the global.cluster.type value
*/}}
{{- define "airbyte.common.cluster.type" }}
    {{- .Values.global.cluster.type }}
{{- end }}

{{/*
Renders the common.cluster.type environment variable
*/}}
{{- define "airbyte.common.cluster.type.env" }}
- name: AIRBYTE_CLUSTER_TYPE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_CLUSTER_TYPE
{{- end }}

{{/*
Renders the global.cluster.name value
*/}}
{{- define "airbyte.common.cluster.name" }}
    {{- .Values.global.cluster.name }}
{{- end }}

{{/*
Renders the common.cluster.name environment variable
*/}}
{{- define "airbyte.common.cluster.name.env" }}
- name: AIRBYTE_CLUSTER_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_CLUSTER_NAME
{{- end }}

{{/*
Renders the global.airbyteUrl value
*/}}
{{- define "airbyte.common.airbyteUrl" }}
    {{- .Values.global.airbyteUrl | default "http://localhost:8080" }}
{{- end }}

{{/*
Renders the common.airbyteUrl environment variable
*/}}
{{- define "airbyte.common.airbyteUrl.env" }}
- name: AIRBYTE_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_URL
{{- end }}

{{/*
Renders the global.api.host value
*/}}
{{- define "airbyte.common.api.host" }}
    {{- .Values.global.api.host | default (ternary (printf "http://localhost:%d/api/public" (int .Values.server.service.port)) (printf "%s/api/public" .Values.global.airbyteUrl) (eq .Values.global.edition "community")) }}
{{- end }}

{{/*
Renders the common.api.host environment variable
*/}}
{{- define "airbyte.common.api.host.env" }}
- name: AIRBYTE_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_API_HOST
{{- end }}

{{/*
Renders the global.server.host value
*/}}
{{- define "airbyte.common.server.host" }}
    {{- (printf "%s-airbyte-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.server.service.port)) }}
{{- end }}

{{/*
Renders the common.server.host environment variable
*/}}
{{- define "airbyte.common.server.host.env" }}
- name: AIRBYTE_SERVER_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: AIRBYTE_SERVER_HOST
{{- end }}

{{/*
Renders the global.auth.enabled value
*/}}
{{- define "airbyte.common.auth.enabled" }}
    {{- .Values.global.auth.enabled | default (ternary "true" "false" (eq .Values.global.edition "enterprise")) }}
{{- end }}

{{/*
Renders the common.auth.enabled environment variable
*/}}
{{- define "airbyte.common.auth.enabled.env" }}
- name: API_AUTHORIZATION_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: API_AUTHORIZATION_ENABLED
{{- end }}

{{/*
Renders the global.connectorBuilderServer.apiHost value
*/}}
{{- define "airbyte.common.connectorBuilderServer.apiHost" }}
    {{- (printf "http://%s-airbyte-connector-builder-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.connectorBuilderServer.service.port)) }}
{{- end }}

{{/*
Renders the common.connectorBuilderServer.apiHost environment variable
*/}}
{{- define "airbyte.common.connectorBuilderServer.apiHost.env" }}
- name: CONNECTOR_BUILDER_SERVER_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_BUILDER_SERVER_API_HOST
{{- end }}

{{/*
Renders the global.manifestServer.apiHost value
*/}}
{{- define "airbyte.common.manifestServer.apiHost" }}
    {{- (printf "http://%s-airbyte-manifest-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.manifestServer.service.port)) }}
{{- end }}

{{/*
Renders the common.manifestServer.apiHost environment variable
*/}}
{{- define "airbyte.common.manifestServer.apiHost.env" }}
- name: MANIFEST_SERVER_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: MANIFEST_SERVER_API_HOST
{{- end }}

{{/*
Renders the global.deploymentEnv value
*/}}
{{- define "airbyte.common.deploymentEnv" }}
    {{- .Values.global.deploymentEnv }}
{{- end }}

{{/*
Renders the common.deploymentEnv environment variable
*/}}
{{- define "airbyte.common.deploymentEnv.env" }}
- name: DEPLOYMENT_ENV
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DEPLOYMENT_ENV
{{- end }}

{{/*
Renders the global.api.internalHost value
*/}}
{{- define "airbyte.common.api.internalHost" }}
    {{- ternary (include "airbyte.common.airbyteUrl" .) (printf "http://%s-airbyte-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.server.service.port)) (eq (include "airbyte.common.cluster.type" .) "data-plane") }}
{{- end }}

{{/*
Renders the common.api.internalHost environment variable
*/}}
{{- define "airbyte.common.api.internalHost.env" }}
- name: INTERNAL_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: INTERNAL_API_HOST
{{- end }}

{{/*
Renders the global.local value
*/}}
{{- define "airbyte.common.local" }}
	{{- if eq .Values.global.local nil }}
    	{{- false }}
	{{- else }}
    	{{- .Values.global.local }}
	{{- end }}
{{- end }}

{{/*
Renders the common.local environment variable
*/}}
{{- define "airbyte.common.local.env" }}
- name: LOCAL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: LOCAL
{{- end }}

{{/*
Renders the global.dummySecret value
*/}}
{{- define "airbyte.common.dummySecret" }}
    {{- .Values.global.dummySecret | default "dummy" }}
{{- end }}

{{/*
Renders the common.dummySecret secret key
*/}}
{{- define "airbyte.common.dummySecret.secretKey" }}
	{{- .Values.global.dummySecretSecretKey | default "AIRBYTE_DUMMY_SECRET" }}
{{- end }}

{{/*
Renders the common.dummySecret environment variable
*/}}
{{- define "airbyte.common.dummySecret.env" }}
- name: AIRBYTE_DUMMY_SECRET
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.common.secretName" . }}
      key: {{ include "airbyte.common.dummySecret.secretKey" . }}
{{- end }}

{{/*
Renders the set of all common environment variables
*/}}
{{- define "airbyte.common.envs" }}
{{- include "airbyte.common.edition.env" . }}
{{- include "airbyte.common.version.env" . }}
{{- include "airbyte.common.cluster.type.env" . }}
{{- include "airbyte.common.cluster.name.env" . }}
{{- include "airbyte.common.airbyteUrl.env" . }}
{{- include "airbyte.common.api.host.env" . }}
{{- include "airbyte.common.server.host.env" . }}
{{- include "airbyte.common.auth.enabled.env" . }}
{{- include "airbyte.common.connectorBuilderServer.apiHost.env" . }}
{{- include "airbyte.common.manifestServer.apiHost.env" . }}
{{- include "airbyte.common.deploymentEnv.env" . }}
{{- include "airbyte.common.api.internalHost.env" . }}
{{- include "airbyte.common.local.env" . }}
{{- include "airbyte.common.dummySecret.env" . }}
{{- end }}

{{/*
Renders the set of all common config map variables
*/}}
{{- define "airbyte.common.configVars" }}
AIRBYTE_EDITION: {{ include "airbyte.common.edition" . | quote }}
AIRBYTE_VERSION: {{ include "airbyte.common.version" . | quote }}
AIRBYTE_CLUSTER_TYPE: {{ include "airbyte.common.cluster.type" . | quote }}
AIRBYTE_CLUSTER_NAME: {{ include "airbyte.common.cluster.name" . | quote }}
AIRBYTE_URL: {{ include "airbyte.common.airbyteUrl" . | quote }}
AIRBYTE_API_HOST: {{ include "airbyte.common.api.host" . | quote }}
AIRBYTE_SERVER_HOST: {{ include "airbyte.common.server.host" . | quote }}
API_AUTHORIZATION_ENABLED: {{ include "airbyte.common.auth.enabled" . | quote }}
CONNECTOR_BUILDER_SERVER_API_HOST: {{ include "airbyte.common.connectorBuilderServer.apiHost" . | quote }}
MANIFEST_SERVER_API_HOST: {{ include "airbyte.common.manifestServer.apiHost" . | quote }}
DEPLOYMENT_ENV: {{ include "airbyte.common.deploymentEnv" . | quote }}
INTERNAL_API_HOST: {{ include "airbyte.common.api.internalHost" . | quote }}
LOCAL: {{ include "airbyte.common.local" . | quote }}
{{- end }}

{{/*
Renders the set of all common secret variables
*/}}
{{- define "airbyte.common.secrets" }}
AIRBYTE_DUMMY_SECRET: {{ include "airbyte.common.dummySecret" . | quote }}
{{- end }}
