
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Connectorrolloutworker Configuration
*/}}

{{/*
Renders the connectorRolloutWorker secret name
*/}}
{{- define "airbyte.connectorRolloutWorker.secretName" }}
{{- if .Values.connectorRolloutWorker.secretName }}
    {{- .Values.connectorRolloutWorker.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the connectorRolloutWorker.githubToken value
*/}}
{{- define "airbyte.connectorRolloutWorker.githubToken" }}
    {{- .Values.connectorRolloutWorker.githubToken }}
{{- end }}

{{/*
Renders the connectorRolloutWorker.githubToken secret key
*/}}
{{- define "airbyte.connectorRolloutWorker.githubToken.secretKey" }}
	{{- .Values.connectorRolloutWorker.githubTokenSecretKey | default "CONNECTOR_ROLLOUT_GITHUB_AIRBYTE_PAT" }}
{{- end }}

{{/*
Renders the connectorRolloutWorker.githubToken environment variable
*/}}
{{- define "airbyte.connectorRolloutWorker.githubToken.env" }}
- name: CONNECTOR_ROLLOUT_GITHUB_AIRBYTE_PAT
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.connectorRolloutWorker.secretName" . }}
      key: {{ include "airbyte.connectorRolloutWorker.githubToken.secretKey" . }}
{{- end }}

{{/*
Renders the set of all connectorRolloutWorker environment variables
*/}}
{{- define "airbyte.connectorRolloutWorker.envs" }}
{{- include "airbyte.connectorRolloutWorker.githubToken.env" . }}
{{- end }}

{{/*
Renders the set of all connectorRolloutWorker secret variables
*/}}
{{- define "airbyte.connectorRolloutWorker.secrets" }}
CONNECTOR_ROLLOUT_GITHUB_AIRBYTE_PAT: {{ include "airbyte.connectorRolloutWorker.githubToken" . | quote }}
{{- end }}
