
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Connectorrollout Configuration
*/}}

{{/*
Renders the global.connectorRollout.expirationSeconds value
*/}}
{{- define "airbyte.connectorRollout.expirationSeconds" }}
    {{- .Values.global.connectorRollout.expirationSeconds | default 604800 }}
{{- end }}

{{/*
Renders the connectorRollout.expirationSeconds environment variable
*/}}
{{- define "airbyte.connectorRollout.expirationSeconds.env" }}
- name: CONNECTOR_ROLLOUT_EXPIRATION_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_ROLLOUT_EXPIRATION_SECONDS
{{- end }}

{{/*
Renders the global.connectorRollout.waitBetweenRolloutSeconds value
*/}}
{{- define "airbyte.connectorRollout.waitBetweenRolloutSeconds" }}
    {{- .Values.global.connectorRollout.waitBetweenRolloutSeconds | default 10800 }}
{{- end }}

{{/*
Renders the connectorRollout.waitBetweenRolloutSeconds environment variable
*/}}
{{- define "airbyte.connectorRollout.waitBetweenRolloutSeconds.env" }}
- name: CONNECTOR_ROLLOUT_WAIT_BETWEEN_ROLLOUTS_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_ROLLOUT_WAIT_BETWEEN_ROLLOUTS_SECONDS
{{- end }}

{{/*
Renders the global.connectorRollout.waitBetweenSyncResultsQueriesSeconds value
*/}}
{{- define "airbyte.connectorRollout.waitBetweenSyncResultsQueriesSeconds" }}
    {{- .Values.global.connectorRollout.waitBetweenSyncResultsQueriesSeconds | default 3600 }}
{{- end }}

{{/*
Renders the connectorRollout.waitBetweenSyncResultsQueriesSeconds environment variable
*/}}
{{- define "airbyte.connectorRollout.waitBetweenSyncResultsQueriesSeconds.env" }}
- name: CONNECTOR_ROLLOUT_WAIT_BETWEEN_SYNC_RESULTS_QUERIES_SECONDS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_ROLLOUT_WAIT_BETWEEN_SYNC_RESULTS_QUERIES_SECONDS
{{- end }}

{{/*
Renders the set of all connectorRollout environment variables
*/}}
{{- define "airbyte.connectorRollout.envs" }}
{{- include "airbyte.connectorRollout.expirationSeconds.env" . }}
{{- include "airbyte.connectorRollout.waitBetweenRolloutSeconds.env" . }}
{{- include "airbyte.connectorRollout.waitBetweenSyncResultsQueriesSeconds.env" . }}
{{- end }}

{{/*
Renders the set of all connectorRollout config map variables
*/}}
{{- define "airbyte.connectorRollout.configVars" }}
CONNECTOR_ROLLOUT_EXPIRATION_SECONDS: {{ include "airbyte.connectorRollout.expirationSeconds" . | quote }}
CONNECTOR_ROLLOUT_WAIT_BETWEEN_ROLLOUTS_SECONDS: {{ include "airbyte.connectorRollout.waitBetweenRolloutSeconds" . | quote }}
CONNECTOR_ROLLOUT_WAIT_BETWEEN_SYNC_RESULTS_QUERIES_SECONDS: {{ include "airbyte.connectorRollout.waitBetweenSyncResultsQueriesSeconds" . | quote }}
{{- end }}

{{/*
Renders the connectorRollout.temporal secret name
*/}}
{{- define "airbyte.connectorRollout.temporal.secretName" }}
{{- if .Values.global.temporal.secretName }}
    {{- .Values.global.temporal.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the global.temporal.cloud.connectorRollout.host value
*/}}
{{- define "airbyte.connectorRollout.temporal.host" }}
    {{- .Values.global.temporal.cloud.connectorRollout.host }}
{{- end }}

{{/*
Renders the connectorRollout.temporal.host environment variable
*/}}
{{- define "airbyte.connectorRollout.temporal.host.env" }}
- name: TEMPORAL_CLOUD_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: TEMPORAL_CLOUD_HOST_CONNECTOR_ROLLOUT
{{- end }}

{{/*
Renders the global.temporal.cloud.connectorRollout.namespace value
*/}}
{{- define "airbyte.connectorRollout.temporal.namespace" }}
    {{- .Values.global.temporal.cloud.connectorRollout.namespace }}
{{- end }}

{{/*
Renders the connectorRollout.temporal.namespace environment variable
*/}}
{{- define "airbyte.connectorRollout.temporal.namespace.env" }}
- name: TEMPORAL_CLOUD_NAMESPACE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: TEMPORAL_CLOUD_NAMESPACE_CONNECTOR_ROLLOUT
{{- end }}

{{/*
Renders the set of all connectorRollout.temporal environment variables
*/}}
{{- define "airbyte.connectorRollout.temporal.envs" }}
{{- include "airbyte.connectorRollout.temporal.host.env" . }}
{{- include "airbyte.connectorRollout.temporal.namespace.env" . }}
{{- end }}

{{/*
Renders the set of all connectorRollout.temporal config map variables
*/}}
{{- define "airbyte.connectorRollout.temporal.configVars" }}
TEMPORAL_CLOUD_HOST_CONNECTOR_ROLLOUT: {{ include "airbyte.connectorRollout.temporal.host" . | quote }}
TEMPORAL_CLOUD_NAMESPACE_CONNECTOR_ROLLOUT: {{ include "airbyte.connectorRollout.temporal.namespace" . | quote }}
{{- end }}
