
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Customerio Configuration
*/}}

{{/*
Renders the customerio secret name
*/}}
{{- define "airbyte.customerio.secretName" }}
{{- if .Values.global.customerio.secretName }}
    {{- .Values.global.customerio.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the global.customerio.apiKey value
*/}}
{{- define "airbyte.customerio.apiKey" }}
    {{- .Values.global.customerio.apiKey }}
{{- end }}

{{/*
Renders the customerio.apiKey secret key
*/}}
{{- define "airbyte.customerio.apiKey.secretKey" }}
	{{- .Values.global.customerio.apiKeySecretKey | default "CUSTOMERIO_API_KEY" }}
{{- end }}

{{/*
Renders the customerio.apiKey environment variable
*/}}
{{- define "airbyte.customerio.apiKey.env" }}
- name: CUSTOMERIO_API_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.customerio.secretName" . }}
      key: {{ include "airbyte.customerio.apiKey.secretKey" . }}
{{- end }}

{{/*
Renders the set of all customerio environment variables
*/}}
{{- define "airbyte.customerio.envs" }}
{{- include "airbyte.customerio.apiKey.env" . }}
{{- end }}

{{/*
Renders the set of all customerio secret variables
*/}}
{{- define "airbyte.customerio.secrets" }}
CUSTOMERIO_API_KEY: {{ include "airbyte.customerio.apiKey" . | quote }}
{{- end }}
