
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Dataplanegroups Configuration
*/}}

{{/*
Renders the global.dataplaneGroups.defaultDataplaneGroupName value
*/}}
{{- define "airbyte.dataplaneGroups.defaultDataplaneGroupName" }}
    {{- .Values.global.dataplaneGroups.defaultDataplaneGroupName }}
{{- end }}

{{/*
Renders the dataplaneGroups.defaultDataplaneGroupName environment variable
*/}}
{{- define "airbyte.dataplaneGroups.defaultDataplaneGroupName.env" }}
- name: DEFAULT_DATAPLANE_GROUP_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DEFAULT_DATAPLANE_GROUP_NAME
{{- end }}

{{/*
Renders the set of all dataplaneGroups environment variables
*/}}
{{- define "airbyte.dataplaneGroups.envs" }}
{{- include "airbyte.dataplaneGroups.defaultDataplaneGroupName.env" . }}
{{- end }}

{{/*
Renders the set of all dataplaneGroups config map variables
*/}}
{{- define "airbyte.dataplaneGroups.configVars" }}
DEFAULT_DATAPLANE_GROUP_NAME: {{ include "airbyte.dataplaneGroups.defaultDataplaneGroupName" . | quote }}
{{- end }}
