
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Featureflags Configuration
*/}}

{{/*
Renders the featureFlags secret name
*/}}
{{- define "airbyte.featureFlags.secretName" }}
{{- if .Values.global.featureFlags.secretName }}
    {{- .Values.global.featureFlags.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the global.featureFlags.client value
*/}}
{{- define "airbyte.featureFlags.client" }}
    {{- .Values.global.featureFlags.client | default "configfile" }}
{{- end }}

{{/*
Renders the featureFlags.client environment variable
*/}}
{{- define "airbyte.featureFlags.client.env" }}
- name: FEATURE_FLAG_CLIENT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: FEATURE_FLAG_CLIENT
{{- end }}

{{/*
Renders the global.featureFlags.configfile.path value
*/}}
{{- define "airbyte.featureFlags.configfile.path" }}
    {{- .Values.global.featureFlags.configfile.path | default "/etc/launchdarkly/flags.yml" }}
{{- end }}

{{/*
Renders the featureFlags.configfile.path environment variable
*/}}
{{- define "airbyte.featureFlags.configfile.path.env" }}
- name: FEATURE_FLAG_PATH
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: FEATURE_FLAG_PATH
{{- end }}

{{/*
Renders the global.featureFlags.launchdarkly.key value
*/}}
{{- define "airbyte.featureFlags.launchdarkly.key" }}
    {{- .Values.global.featureFlags.launchdarkly.key }}
{{- end }}

{{/*
Renders the featureFlags.launchdarkly.key secret key
*/}}
{{- define "airbyte.featureFlags.launchdarkly.key.secretKey" }}
	{{- .Values.global.featureFlags.launchdarkly.keySecretKey | default "LAUNCHDARKLY_KEY" }}
{{- end }}

{{/*
Renders the featureFlags.launchdarkly.key environment variable
*/}}
{{- define "airbyte.featureFlags.launchdarkly.key.env" }}
- name: LAUNCHDARKLY_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.featureFlags.secretName" . }}
      key: {{ include "airbyte.featureFlags.launchdarkly.key.secretKey" . }}
{{- end }}

{{/*
Renders the set of all featureFlags environment variables
*/}}
{{- define "airbyte.featureFlags.envs" }}
{{- include "airbyte.featureFlags.client.env" . }}
{{- $opt := (include "airbyte.featureFlags.client" .) }}

{{- if eq $opt "configfile" }}
{{- include "airbyte.featureFlags.configfile.path.env" . }}
{{- end }}

{{- if eq $opt "launchdarkly" }}
{{- include "airbyte.featureFlags.launchdarkly.key.env" . }}
{{- end }}

{{- end }}

{{/*
Renders the set of all featureFlags config map variables
*/}}
{{- define "airbyte.featureFlags.configVars" }}
FEATURE_FLAG_CLIENT: {{ include "airbyte.featureFlags.client" . | quote }}
{{- $opt := (include "airbyte.featureFlags.client" .) }}

{{- if eq $opt "configfile" }}
FEATURE_FLAG_PATH: {{ include "airbyte.featureFlags.configfile.path" . | quote }}
{{- end }}

{{- if eq $opt "launchdarkly" }}
{{- end }}

{{- end }}

{{/*
Renders the set of all featureFlags secret variables
*/}}
{{- define "airbyte.featureFlags.secrets" }}
{{- $opt := (include "airbyte.featureFlags.client" .) }}

{{- if eq $opt "configfile" }}
{{- end }}

{{- if eq $opt "launchdarkly" }}
LAUNCHDARKLY_KEY: {{ include "airbyte.featureFlags.launchdarkly.key" . | quote }}
{{- end }}

{{- end }}
