
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Java Configuration
*/}}

{{/*
Renders the global.java.opts value
*/}}
{{- define "airbyte.java.opts" }}
    {{- join " " .Values.global.java.opts }}
{{- end }}

{{/*
Renders the java.opts environment variable
*/}}
{{- define "airbyte.java.opts.env" }}
- name: JAVA_TOOL_OPTIONS
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: JAVA_TOOL_OPTIONS
{{- end }}

{{/*
Renders the set of all java environment variables
*/}}
{{- define "airbyte.java.envs" }}
{{- include "airbyte.java.opts.env" . }}
{{- end }}

{{/*
Renders the set of all java config map variables
*/}}
{{- define "airbyte.java.configVars" }}
JAVA_TOOL_OPTIONS: {{ include "airbyte.java.opts" . | quote }}
{{- end }}
