
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Logging Configuration
*/}}

{{/*
Renders the global.logging.level value
*/}}
{{- define "airbyte.logging.level" }}
    {{- .Values.global.logging.level | default "INFO" }}
{{- end }}

{{/*
Renders the logging.level environment variable
*/}}
{{- define "airbyte.logging.level.env" }}
- name: LOG_LEVEL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: LOG_LEVEL
{{- end }}

{{/*
Renders the set of all logging environment variables
*/}}
{{- define "airbyte.logging.envs" }}
{{- include "airbyte.logging.level.env" . }}
{{- end }}

{{/*
Renders the set of all logging config map variables
*/}}
{{- define "airbyte.logging.configVars" }}
LOG_LEVEL: {{ include "airbyte.logging.level" . | quote }}
{{- end }}
