
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Minio Configuration
*/}}

{{/*
Renders the minio.rootUser value
*/}}
{{- define "airbyte.minio.rootUser" }}
    {{- .Values.minio.rootUser }}
{{- end }}

{{/*
Renders the minio.rootUser secret key
*/}}
{{- define "airbyte.minio.rootUser.secretKey" }}
	{{- .Values.minio.rootUserSecretKey | default "AWS_ACCESS_KEY_ID" }}
{{- end }}

{{/*
Renders the minio.rootUser environment variable
*/}}
{{- define "airbyte.minio.rootUser.env" }}
- name: MINIO_ROOT_USER
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.storage.secretName" . }}
      key: {{ include "airbyte.minio.rootUser.secretKey" . }}
{{- end }}

{{/*
Renders the minio.rootPassword value
*/}}
{{- define "airbyte.minio.rootPassword" }}
    {{- .Values.minio.rootPassword }}
{{- end }}

{{/*
Renders the minio.rootPassword secret key
*/}}
{{- define "airbyte.minio.rootPassword.secretKey" }}
	{{- .Values.minio.rootPasswordSecretKey | default "AWS_SECRET_ACCESS_KEY" }}
{{- end }}

{{/*
Renders the minio.rootPassword environment variable
*/}}
{{- define "airbyte.minio.rootPassword.env" }}
- name: MINIO_ROOT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.storage.secretName" . }}
      key: {{ include "airbyte.minio.rootPassword.secretKey" . }}
{{- end }}

{{/*
Renders the set of all minio environment variables
*/}}
{{- define "airbyte.minio.envs" }}
{{- include "airbyte.minio.rootUser.env" . }}
{{- include "airbyte.minio.rootPassword.env" . }}
{{- end }}
