
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Otel Configuration
*/}}

{{/*
Renders the global.metrics.otel.exporter.endpoint value
*/}}
{{- define "airbyte.otel.exporter.endpoint" }}
    {{- .Values.global.metrics.otel.exporter.endpoint | default (ternary "http://${DD_AGENT_HOST}:4317" "" .Values.global.datadog.enabled) }}
{{- end }}

{{/*
Renders the otel.exporter.endpoint environment variable
*/}}
{{- define "airbyte.otel.exporter.endpoint.env" }}
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: OTEL_EXPORTER_OTLP_ENDPOINT
{{- end }}

{{/*
Renders the global.metrics.otel.exporter.protocol value
*/}}
{{- define "airbyte.otel.exporter.protocol" }}
    {{- .Values.global.metrics.otel.exporter.protocol | default "grpc" }}
{{- end }}

{{/*
Renders the otel.exporter.protocol environment variable
*/}}
{{- define "airbyte.otel.exporter.protocol.env" }}
- name: OTEL_EXPORTER_OTLP_PROTOCOL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: OTEL_EXPORTER_OTLP_PROTOCOL
{{- end }}

{{/*
Renders the global.metrics.otel.exporter.timeout value
*/}}
{{- define "airbyte.otel.exporter.timeout" }}
    {{- .Values.global.metrics.otel.exporter.timeout | default 30000 }}
{{- end }}

{{/*
Renders the otel.exporter.timeout environment variable
*/}}
{{- define "airbyte.otel.exporter.timeout.env" }}
- name: OTEL_EXPORTER_OTLP_TIMEOUT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: OTEL_EXPORTER_OTLP_TIMEOUT
{{- end }}

{{/*
Renders the global.metrics.otel.exporter.metricExportInterval value
*/}}
{{- define "airbyte.otel.exporter.metricExportInterval" }}
    {{- .Values.global.metrics.otel.exporter.metricExportInterval | default 10000 }}
{{- end }}

{{/*
Renders the otel.exporter.metricExportInterval environment variable
*/}}
{{- define "airbyte.otel.exporter.metricExportInterval.env" }}
- name: OTEL_METRIC_EXPORT_INTERVAL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: OTEL_METRIC_EXPORT_INTERVAL
{{- end }}

{{/*
Renders the global.metrics.otel.exporter.name value
*/}}
{{- define "airbyte.otel.exporter.name" }}
    {{- .Values.global.metrics.otel.exporter.name | default "otlp" }}
{{- end }}

{{/*
Renders the otel.exporter.name environment variable
*/}}
{{- define "airbyte.otel.exporter.name.env" }}
- name: OTEL_METRICS_EXPORTER
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: OTEL_METRICS_EXPORTER
{{- end }}

{{/*
Renders the global.metrics.otel.resourceAttributes value
*/}}
{{- define "airbyte.otel.resourceAttributes" }}
    {{- .Values.global.metrics.otel.resourceAttributes | default (printf "service.name=%s,deployment.environment=%s,service.version=%s" (include "airbyte.componentName" .) .Values.global.env (include "airbyte.common.version" .)) }}
{{- end }}

{{/*
Renders the otel.resourceAttributes environment variable
*/}}
{{- define "airbyte.otel.resourceAttributes.env" }}
- name: OTEL_RESOURCE_ATTRIBUTES
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: OTEL_RESOURCE_ATTRIBUTES
{{- end }}

{{/*
Renders the set of all otel environment variables
*/}}
{{- define "airbyte.otel.envs" }}
{{- include "airbyte.otel.exporter.endpoint.env" . }}
{{- include "airbyte.otel.exporter.protocol.env" . }}
{{- include "airbyte.otel.exporter.timeout.env" . }}
{{- include "airbyte.otel.exporter.metricExportInterval.env" . }}
{{- include "airbyte.otel.exporter.name.env" . }}
{{- include "airbyte.otel.resourceAttributes.env" . }}
{{- end }}

{{/*
Renders the set of all otel config map variables
*/}}
{{- define "airbyte.otel.configVars" }}
OTEL_EXPORTER_OTLP_ENDPOINT: {{ include "airbyte.otel.exporter.endpoint" . | quote }}
OTEL_EXPORTER_OTLP_PROTOCOL: {{ include "airbyte.otel.exporter.protocol" . | quote }}
OTEL_EXPORTER_OTLP_TIMEOUT: {{ include "airbyte.otel.exporter.timeout" . | quote }}
OTEL_METRIC_EXPORT_INTERVAL: {{ include "airbyte.otel.exporter.metricExportInterval" . | quote }}
OTEL_METRICS_EXPORTER: {{ include "airbyte.otel.exporter.name" . | quote }}
OTEL_RESOURCE_ATTRIBUTES: {{ include "airbyte.otel.resourceAttributes" . | quote }}
{{- end }}
