
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Shopify Configuration
*/}}

{{/*
Renders the shopify secret name
*/}}
{{- define "airbyte.shopify.secretName" }}
{{- if .Values.global.shopify.secretName }}
    {{- .Values.global.shopify.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the global.shopify.clientId value
*/}}
{{- define "airbyte.shopify.clientId" }}
    {{- .Values.global.shopify.clientId }}
{{- end }}

{{/*
Renders the shopify.clientId secret key
*/}}
{{- define "airbyte.shopify.clientId.secretKey" }}
	{{- .Values.global.shopify.clientIdSecretKey | default "SHOPIFY_CLIENT_ID" }}
{{- end }}

{{/*
Renders the shopify.clientId environment variable
*/}}
{{- define "airbyte.shopify.clientId.env" }}
- name: SHOPIFY_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.shopify.secretName" . }}
      key: {{ include "airbyte.shopify.clientId.secretKey" . }}
{{- end }}

{{/*
Renders the global.shopify.apiSecretKey value
*/}}
{{- define "airbyte.shopify.apiSecretKey" }}
    {{- .Values.global.shopify.apiSecretKey }}
{{- end }}

{{/*
Renders the shopify.apiSecretKey secret key
*/}}
{{- define "airbyte.shopify.apiSecretKey.secretKey" }}
	{{- .Values.global.shopify.apiSecretKeySecretKey | default "SHOPIFY_API_SECRET_KEY" }}
{{- end }}

{{/*
Renders the shopify.apiSecretKey environment variable
*/}}
{{- define "airbyte.shopify.apiSecretKey.env" }}
- name: SHOPIFY_API_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte.shopify.secretName" . }}
      key: {{ include "airbyte.shopify.apiSecretKey.secretKey" . }}
{{- end }}

{{/*
Renders the set of all shopify environment variables
*/}}
{{- define "airbyte.shopify.envs" }}
{{- include "airbyte.shopify.clientId.env" . }}
{{- include "airbyte.shopify.apiSecretKey.env" . }}
{{- end }}

{{/*
Renders the set of all shopify secret variables
*/}}
{{- define "airbyte.shopify.secrets" }}
SHOPIFY_CLIENT_ID: {{ include "airbyte.shopify.clientId" . | quote }}
SHOPIFY_API_SECRET_KEY: {{ include "airbyte.shopify.apiSecretKey" . | quote }}
{{- end }}
