
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Webapp Configuration
*/}}

{{/*
Renders the webapp.api.url value
*/}}
{{- define "airbyte.webapp.api.url" }}
    {{- "/api/v1" }}
{{- end }}

{{/*
Renders the webapp.api.url environment variable
*/}}
{{- define "airbyte.webapp.api.url.env" }}
- name: API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: API_URL
{{- end }}

{{/*
Renders the set of all webapp environment variables
*/}}
{{- define "airbyte.webapp.envs" }}
{{- include "airbyte.webapp.api.url.env" . }}
{{- end }}

{{/*
Renders the set of all webapp config map variables
*/}}
{{- define "airbyte.webapp.configVars" }}
API_URL: {{ include "airbyte.webapp.api.url" . | quote }}
{{- end }}
