
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Webapp Configuration
*/}}

{{/*
Renders the webapp.api.url environment variable
*/}}
{{- define "airbyte.webapp.api.url.env" }}
- name: API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: API_URL
{{- end }}

{{/*
Renders the webapp.connectorBuilderServer.host value
*/}}
{{- define "airbyte.webapp.connectorBuilderServer.host" }}
    {{- (printf "%s-airbyte-connector-builder-server-svc:%d" .Release.Name (int .Values.connectorBuilderServer.service.port)) }}
{{- end }}

{{/*
Renders the webapp.connectorBuilderServer.host environment variable
*/}}
{{- define "airbyte.webapp.connectorBuilderServer.host.env" }}
- name: CONNECTOR_BUILDER_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_BUILDER_API_HOST
{{- end }}

{{/*
Renders the webapp.connectorBuilderServer.url value
*/}}
{{- define "airbyte.webapp.connectorBuilderServer.url" }}
    {{- .Values.webapp.connectorBuilderServer.url | default "/connector-builder-api" }}
{{- end }}

{{/*
Renders the webapp.connectorBuilderServer.url environment variable
*/}}
{{- define "airbyte.webapp.connectorBuilderServer.url.env" }}
- name: CONNECTOR_BUILDER_API_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_BUILDER_API_URL
{{- end }}

{{/*
Renders the set of all webapp environment variables
*/}}
{{- define "airbyte.webapp.envs" }}
{{- include "airbyte.webapp.api.url.env" . }}
{{- include "airbyte.webapp.connectorBuilderServer.host.env" . }}
{{- include "airbyte.webapp.connectorBuilderServer.url.env" . }}
{{- end }}

{{/*
Renders the set of all webapp config map variables
*/}}
{{- define "airbyte.webapp.configVars" }}
API_URL: {{ "/api/v1" | quote }}
CONNECTOR_BUILDER_API_HOST: {{ (printf "%s-airbyte-connector-builder-server-svc:%d" .Release.Name (int .Values.connectorBuilderServer.service.port)) | quote }}
CONNECTOR_BUILDER_API_URL: {{ include "airbyte.webapp.connectorBuilderServer.url" . | quote }}
{{- end }}
