
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Workloadlauncher Configuration
*/}}

{{/*
Renders the workloadLauncher.controlPlane.tokenEndpoint value
*/}}
{{- define "airbyte.workloadLauncher.controlPlane.tokenEndpoint" }}
    {{- (printf "%s/api/v1/dataplanes/token" (ternary (include "airbyte.common.airbyteUrl" .) (printf "http://%s-airbyte-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.server.service.port)) (eq (include "airbyte.common.cluster.type" .) "data-plane"))) }}
{{- end }}

{{/*
Renders the workloadLauncher.controlPlane.tokenEndpoint environment variable
*/}}
{{- define "airbyte.workloadLauncher.controlPlane.tokenEndpoint.env" }}
- name: CONTROL_PLANE_TOKEN_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONTROL_PLANE_TOKEN_ENDPOINT
{{- end }}

{{/*
Renders the workloadLauncher.enabled value
*/}}
{{- define "airbyte.workloadLauncher.enabled" }}
	{{- if eq .Values.workloadLauncher.enabled nil }}
    	{{- true }}
	{{- else }}
    	{{- .Values.workloadLauncher.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the workloadLauncher.enabled environment variable
*/}}
{{- define "airbyte.workloadLauncher.enabled.env" }}
- name: WORKLOAD_LAUNCHER_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_LAUNCHER_ENABLED
{{- end }}

{{/*
Renders the workloadLauncher.parallelism value
*/}}
{{- define "airbyte.workloadLauncher.parallelism" }}
    {{- .Values.workloadLauncher.parallelism | default 10 }}
{{- end }}

{{/*
Renders the workloadLauncher.parallelism environment variable
*/}}
{{- define "airbyte.workloadLauncher.parallelism.env" }}
- name: WORKLOAD_LAUNCHER_PARALLELISM
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_LAUNCHER_PARALLELISM
{{- end }}

{{/*
Renders the set of all workloadLauncher environment variables
*/}}
{{- define "airbyte.workloadLauncher.envs" }}
{{- include "airbyte.workloadLauncher.controlPlane.tokenEndpoint.env" . }}
{{- include "airbyte.workloadLauncher.enabled.env" . }}
{{- include "airbyte.workloadLauncher.parallelism.env" . }}
{{- end }}

{{/*
Renders the set of all workloadLauncher config map variables
*/}}
{{- define "airbyte.workloadLauncher.configVars" }}
CONTROL_PLANE_TOKEN_ENDPOINT: {{ include "airbyte.workloadLauncher.controlPlane.tokenEndpoint" . | quote }}
WORKLOAD_LAUNCHER_ENABLED: {{ include "airbyte.workloadLauncher.enabled" . | quote }}
WORKLOAD_LAUNCHER_PARALLELISM: {{ include "airbyte.workloadLauncher.parallelism" . | quote }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane secret name
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.secretName" }}
{{- if .Values.workloadLauncher.dataPlane.secretName }}
    {{- .Values.workloadLauncher.dataPlane.secretName }}
{{- else }}
    {{- .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientId value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId" }}
    {{- .Values.workloadLauncher.dataPlane.clientId }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientId secret key
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId.secretKey" }}
	{{- .Values.workloadLauncher.dataPlane.clientIdSecretKey | default (include "airbyte.auth.bootstrap.dataPlane.clientIdSecretKey" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientId environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientId.env" }}
- name: DATAPLANE_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: {{ (ternary (include "airbyte.auth.bootstrap.managedSecretName" .) (include "airbyte.workloadLauncher.dataPlane.secretName" .) (eq (include "airbyte.common.cluster.type" .) "hybrid")) }}
      key: {{ include "airbyte.workloadLauncher.dataPlane.clientId.secretKey" . }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretName value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretName" }}
    {{- .Values.workloadLauncher.dataPlane.clientIdSecretName | default (include "airbyte.auth.bootstrap.managedSecretName" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretName environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretName.env" }}
- name: DATAPLANE_CLIENT_ID_SECRET_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_ID_SECRET_NAME
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretKey value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretKey" }}
    {{- .Values.workloadLauncher.dataPlane.clientIdSecretKey | default (include "airbyte.auth.bootstrap.dataPlane.clientIdSecretKey" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientIdSecretKey environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientIdSecretKey.env" }}
- name: DATAPLANE_CLIENT_ID_SECRET_KEY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_ID_SECRET_KEY
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecret value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret" }}
    {{- .Values.workloadLauncher.dataPlane.clientSecret }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecret secret key
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret.secretKey" }}
	{{- .Values.workloadLauncher.dataPlane.clientSecretSecretKey | default (include "airbyte.auth.bootstrap.dataPlane.clientSecretSecretKey" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecret environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecret.env" }}
- name: DATAPLANE_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: {{ (ternary (include "airbyte.auth.bootstrap.managedSecretName" .) (include "airbyte.workloadLauncher.dataPlane.secretName" .) (eq (include "airbyte.common.cluster.type" .) "hybrid")) }}
      key: {{ include "airbyte.workloadLauncher.dataPlane.clientSecret.secretKey" . }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretName value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretName" }}
    {{- .Values.workloadLauncher.dataPlane.clientSecretSecretName | default (include "airbyte.auth.bootstrap.managedSecretName" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretName environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretName.env" }}
- name: DATAPLANE_CLIENT_SECRET_SECRET_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_SECRET_SECRET_NAME
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretKey value
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey" }}
    {{- .Values.workloadLauncher.dataPlane.clientSecretSecretKey | default (include "airbyte.auth.bootstrap.dataPlane.clientSecretSecretKey" .) }}
{{- end }}

{{/*
Renders the workloadLauncher.dataPlane.clientSecretSecretKey environment variable
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey.env" }}
- name: DATAPLANE_CLIENT_SECRET_SECRET_KEY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: DATAPLANE_CLIENT_SECRET_SECRET_KEY
{{- end }}

{{/*
Renders the set of all workloadLauncher.dataPlane environment variables
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.envs" }}
{{- include "airbyte.workloadLauncher.dataPlane.clientId.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientIdSecretName.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientIdSecretKey.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientSecret.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientSecretSecretName.env" . }}
{{- include "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey.env" . }}
{{- end }}

{{/*
Renders the set of all workloadLauncher.dataPlane config map variables
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.configVars" }}
DATAPLANE_CLIENT_ID_SECRET_NAME: {{ include "airbyte.workloadLauncher.dataPlane.clientIdSecretName" . | quote }}
DATAPLANE_CLIENT_ID_SECRET_KEY: {{ include "airbyte.workloadLauncher.dataPlane.clientIdSecretKey" . | quote }}
DATAPLANE_CLIENT_SECRET_SECRET_NAME: {{ include "airbyte.workloadLauncher.dataPlane.clientSecretSecretName" . | quote }}
DATAPLANE_CLIENT_SECRET_SECRET_KEY: {{ include "airbyte.workloadLauncher.dataPlane.clientSecretSecretKey" . | quote }}
{{- end }}

{{/*
Renders the set of all workloadLauncher.dataPlane secret variables
*/}}
{{- define "airbyte.workloadLauncher.dataPlane.secrets" }}
DATAPLANE_CLIENT_ID: {{ include "airbyte.workloadLauncher.dataPlane.clientId" . | quote }}
DATAPLANE_CLIENT_SECRET: {{ include "airbyte.workloadLauncher.dataPlane.clientSecret" . | quote }}
{{- end }}

{{/*
Renders the global.image.registry value
*/}}
{{- define "airbyte.workloadLauncher.images.registry" }}
    {{- .Values.global.image.registry }}
{{- end }}

{{/*
Renders the workloadLauncher.images.registry environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.registry.env" }}
- name: JOB_KUBE_CONNECTOR_IMAGE_REGISTRY
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: JOB_KUBE_CONNECTOR_IMAGE_REGISTRY
{{- end }}

{{/*
Renders the workloadLauncher.connectorProfiler.image value
*/}}
{{- define "airbyte.workloadLauncher.images.connectorProfiler.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.connectorProfiler.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.connectorProfiler.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.connectorProfiler.image.env" }}
- name: CONNECTOR_PROFILER_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_PROFILER_IMAGE
{{- end }}

{{/*
Renders the workloadLauncher.connectorSidecar.image value
*/}}
{{- define "airbyte.workloadLauncher.images.connectorSidecar.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.connectorSidecar.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.connectorSidecar.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.connectorSidecar.image.env" }}
- name: CONNECTOR_SIDECAR_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONNECTOR_SIDECAR_IMAGE
{{- end }}

{{/*
Renders the workloadLauncher.containerOrchestrator.enabled value
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.enabled" }}
    {{- .Values.workloadLauncher.containerOrchestrator.enabled }}
{{- end }}

{{/*
Renders the workloadLauncher.images.containerOrchestrator.enabled environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.enabled.env" }}
- name: CONTAINER_ORCHESTRATOR_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONTAINER_ORCHESTRATOR_ENABLED
{{- end }}

{{/*
Renders the workloadLauncher.containerOrchestrator.image value
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.containerOrchestrator.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.containerOrchestrator.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.containerOrchestrator.image.env" }}
- name: CONTAINER_ORCHESTRATOR_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: CONTAINER_ORCHESTRATOR_IMAGE
{{- end }}

{{/*
Renders the workloadLauncher.workloadInit.image value
*/}}
{{- define "airbyte.workloadLauncher.images.workloadInit.image" }}
    {{- include "imageUrl" (list .Values.workloadLauncher.workloadInit.image $) }}
{{- end }}

{{/*
Renders the workloadLauncher.images.workloadInit.image environment variable
*/}}
{{- define "airbyte.workloadLauncher.images.workloadInit.image.env" }}
- name: WORKLOAD_INIT_IMAGE
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_INIT_IMAGE
{{- end }}

{{/*
Renders the set of all workloadLauncher.images environment variables
*/}}
{{- define "airbyte.workloadLauncher.images.envs" }}
{{- include "airbyte.workloadLauncher.images.registry.env" . }}
{{- include "airbyte.workloadLauncher.images.connectorProfiler.image.env" . }}
{{- include "airbyte.workloadLauncher.images.connectorSidecar.image.env" . }}
{{- include "airbyte.workloadLauncher.images.containerOrchestrator.enabled.env" . }}
{{- include "airbyte.workloadLauncher.images.containerOrchestrator.image.env" . }}
{{- include "airbyte.workloadLauncher.images.workloadInit.image.env" . }}
{{- end }}

{{/*
Renders the set of all workloadLauncher.images config map variables
*/}}
{{- define "airbyte.workloadLauncher.images.configVars" }}
JOB_KUBE_CONNECTOR_IMAGE_REGISTRY: {{ include "airbyte.workloadLauncher.images.registry" . | quote }}
CONNECTOR_PROFILER_IMAGE: {{ include "airbyte.workloadLauncher.images.connectorProfiler.image" . | quote }}
CONNECTOR_SIDECAR_IMAGE: {{ include "airbyte.workloadLauncher.images.connectorSidecar.image" . | quote }}
CONTAINER_ORCHESTRATOR_ENABLED: {{ include "airbyte.workloadLauncher.images.containerOrchestrator.enabled" . | quote }}
CONTAINER_ORCHESTRATOR_IMAGE: {{ include "airbyte.workloadLauncher.images.containerOrchestrator.image" . | quote }}
WORKLOAD_INIT_IMAGE: {{ include "airbyte.workloadLauncher.images.workloadInit.image" . | quote }}
{{- end }}
