
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Workloadapiserver Configuration
*/}}

{{/*
Renders the workloadApiServer.enabled value
*/}}
{{- define "airbyte.workloadApiServer.enabled" }}
	{{- if eq .Values.workloadApiServer.enabled nil }}
    	{{- true }}
	{{- else }}
    	{{- .Values.workloadApiServer.enabled }}
	{{- end }}
{{- end }}

{{/*
Renders the workloadApiServer.enabled environment variable
*/}}
{{- define "airbyte.workloadApiServer.enabled.env" }}
- name: WORKLOAD_API_SERVER_ENABLED
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_API_SERVER_ENABLED
{{- end }}

{{/*
Renders the workloadApiServer.host value
*/}}
{{- define "airbyte.workloadApiServer.host" }}
    {{- ternary (include "airbyte.common.airbyteUrl" .) (printf "http://%s-workload-api-server-svc.%s:%d" .Release.Name .Release.Namespace (int .Values.workloadApiServer.service.port)) (eq (include "airbyte.cluster.type" .) "data-plane") }}
{{- end }}

{{/*
Renders the workloadApiServer.host environment variable
*/}}
{{- define "airbyte.workloadApiServer.host.env" }}
- name: WORKLOAD_API_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-env
      key: WORKLOAD_API_HOST
{{- end }}

{{/*
Renders the set of all workloadApiServer environment variables
*/}}
{{- define "airbyte.workloadApiServer.envs" }}
{{- include "airbyte.workloadApiServer.enabled.env" . }}
{{- include "airbyte.workloadApiServer.host.env" . }}
{{- end }}

{{/*
Renders the set of all workloadApiServer config map variables
*/}}
{{- define "airbyte.workloadApiServer.configVars" }}
WORKLOAD_API_SERVER_ENABLED: {{ include "airbyte.workloadApiServer.enabled" . | quote }}
WORKLOAD_API_HOST: {{ include "airbyte.workloadApiServer.host" . | quote }}
{{- end }}
