/*
 * Copyright (c) 2020-2025 Airbyte, Inc., all rights reserved.
 */

package io.airbyte.data.services

import io.airbyte.data.repositories.DataplaneHeartbeatLogRepository
import io.airbyte.data.repositories.entities.DataplaneHeartbeatLog
import io.github.oshai.kotlinlogging.KotlinLogging
import jakarta.inject.Singleton
import java.util.UUID

private val logger = KotlinLogging.logger {}

/**
 * Service for managing dataplane health monitoring and heartbeat logging.
 */
@Singleton
class DataplaneHealthService(
  private val heartbeatLogRepository: DataplaneHeartbeatLogRepository,
) {
  companion object {
    const val UNKNOWN_VERSION = "unknown"
  }

  /**
   * Record a heartbeat for a dataplane.
   * Timestamp is auto-generated by database (created_at column).
   */
  fun recordHeartbeat(
    dataplaneId: UUID,
    controlPlaneVersion: String? = null,
    dataplaneVersion: String? = null,
  ) {
    val log =
      DataplaneHeartbeatLog(
        dataplaneId = dataplaneId,
        controlPlaneVersion = controlPlaneVersion ?: UNKNOWN_VERSION,
        dataplaneVersion = dataplaneVersion ?: UNKNOWN_VERSION,
      )

    heartbeatLogRepository.save(log)
    logger.debug { "Recorded heartbeat for dataplane $dataplaneId" }
  }
}
