# Create secrets only for the local deployment
{{- if .Values.workloadLauncher.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: workload-launcher-secrets
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  {{- range $k, $v := mergeOverwrite .Values.workloadLauncher.secrets .Values.global.secrets }}
  {{ $k }}: {{ if $v }}{{ $v | b64enc  }} {{else}}""{{end}}
  {{- end }}
{{- end }}
