{{- if .Values.server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "airbyte.namespace" . }}
  name: {{.Release.Name }}-airbyte-server-svc
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  {{- with .Values.server.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- if and .Values.server.service.externalTrafficPolicy (or (eq .Values.server.service.type "NodePort") (eq .Values.server.service.type "LoadBalancer")) }}
  externalTrafficPolicy: {{ .Values.server.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.server.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- with .Values.server.service.appProtocol }}
    appProtocol: {{ . }}
    {{- end }}
    {{- if and (or (eq .Values.server.service.type "NodePort") (eq .Values.server.service.type "LoadBalancer")) .Values.server.service.nodePort }}
    nodePort: {{ .Values.server.service.nodePort }}
    {{- end }}
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.server.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.server.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
{{- end }}
