{{- if .Values.webapp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-airbyte-webapp-svc
  {{- with .Values.webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
  - port: {{ .Values.webapp.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{ if and (eq .Values.webapp.service.type "NodePort") (.Values.webapp.service.nodePort)  }}
    nodePort: {{ .Values.webapp.service.nodePort }}
    {{- end }}
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.webapp.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.webapp.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
  {{- if .Values.webapp.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webapp.service.loadBalancerIP }}
  {{- end }}
{{- end }}
