{{- if and 
  (or (eq .Values.global.edition "community") (eq .Values.global.edition "enterprise"))
  (eq (lower (default "" .Values.global.storage.type)) "gcs") 
  (not .Values.global.storage.secretName)
  (not .Values.global.storage.storageSecretName)
}}
{{ $gcsConfig := required "You must set 'global.storage.gcs' when setting 'global.storage.type' to 'gcs'" .Values.global.storage.gcs }}
{{ $credentialsJson := required  "You must set 'global.storage.gcs.credentialsJson' when 'global.storage.secretName' is not set" .Values.global.storage.gcs.credentialsJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcs-log-creds
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
type: Opaque
data:
  gcp.json: {{ $credentialsJson | default ""  | quote }}
{{- end }}
