name: Check for broken links in FE

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  validate-frontend-links:
    name: "Validate frontend links"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Run :oss:airbyte-webapp:validateLinks
        run: ./gradlew --no-daemon :oss:airbyte-webapp:validateLinks --scan -DciMode=true

      - name: Publish Failures to dev-frontend channel
        uses: abinoda/slack-action@master
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          args: >-
            {\"channel\":\"C03088BTMFC\", \"blocks\":[
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\":alarm: The periodic link validation failed!\n\n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"See details on <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|GitHub>\n\"}}]}
