name: Create Cloud PR from OSS PR
on:
  issue_comment:
    types: [created]
jobs:
  check:
      if: startsWith(github.head_ref, 'main') != true
      runs-on: ubuntu-18.04
      steps:
        - uses: xt0rted/pull-request-comment-branch@v1
          id: comment-branch
        - uses: actions/checkout@v3
          with:
            ref: ${{ steps.comment-branch.outputs.head_ref }}
            fetch-depth: 0 # needed to have the base branch available for the action below
        - uses: stefanluptak/check-branch-up-to-date@v1
          with:
            base_branch: 'main'
            head_branch: ${{ steps.comment-branch.outputs.head_ref }}

  dispatch_command_to_cloud:
    needs: check
    #if: needs.check.outputs.up_to_date == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Create a snapshot of an OSS PR to Cloud
        uses: peter-evans/slash-command-dispatch@v3
        id: slash-command-dispatch
        with:
          token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
          permission: write
          issue-type: pull-request
          repository: airbytehq/oss-to-cloud-action-test
          dispatch-type: repository
          static-args: |
            repository=${{ github.repository }}
            branch=${{ needs.check.comment-branch.outputs.head_ref }}
          commands: |
            create-cloud-pr

      - name: Publish comment with error message
        if: steps.slash-command-dispatch.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > Error: ${{ steps.slash-command-dispatch.outputs.error-message }}
