name: Publish OSS Artifacts for Cloud

env:
  # enable gradle remote build cache
  S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
  S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}

on:
  workflow_dispatch:
    inputs:
      oss_ref:
        description: "Publish artifacts for the following git ref (if unspecified, uses the latest commit for the current branch):"
        required: false
jobs:
  start-runner:
    name: "Start Runner on AWS"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
      - name: Check PAT rate limits
        run: |
          ./tools/bin/find_non_rate_limited_PAT \
            ${{ secrets.GH_PAT_BUILD_RUNNER_OSS }} \
            ${{ secrets.GH_PAT_BUILD_RUNNER_BACKUP }}
      - name: Start AWS Runner
        id: start-ec2-runner
        uses: ./.github/actions/start-aws-runner
        with:
          aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ env.PAT }}

  generate-tags:
    name: "Generate Dev and Main Tags"
    runs-on: ubuntu-latest
    outputs:
      dev_tag: ${{ steps.set-outputs.outputs.dev_tag }}
      main_tag: ${{ steps.set-outputs.outputs.main_tag }}
    steps:
      - name: Checkout Airbyte Platform
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.oss_ref || github.ref }}
      - name: Generate Outputs
        id: set-outputs
        shell: bash
        run: |-
          set -x

          commit_sha=$(git rev-parse --short=10 HEAD)

          # set dev_tag
          # AirbyteVersion.java allows versions that have a prefix of 'dev'
          echo "dev_tag=dev-${commit_sha}" >> $GITHUB_OUTPUT

          # If this commit is on the main branch, also set main_tag
          if $(git merge-base --is-ancestor "${commit_sha}" main); then
            echo "main_tag=${commit_sha}" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT || true # for the sake of investigation

  oss-branch-build:
    concurrency:
      # only allow one workflow run at a time for a given SHA
      # to prevent multiple runs from pushing artifacts for the same SHA at the same time
      # note: using inputs in the group expression only works when specifying concurrency at the job level
      group: ${{ github.workflow }}-${{ inputs.oss_ref || github.sha }}
      cancel-in-progress: false
    name: "Gradle Build and Publish"
    needs:
      - start-runner
      - generate-tags
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.oss_ref || github.ref }}

      # TODO: Once we pull these from the metadata service, remove this step. Also we can't build the webapp locally
      #       since docs are not pulled when running gradle locally.
      - name: Copy docs from connectors repository
        run: |
          git clone --depth 1 https://.:${{ secrets.GITHUB_TOKEN }}@github.com/airbytehq/airbyte /tmp/airbyte_repo
          mkdir -p ./docs
          cp -R /tmp/airbyte_repo/docs/integrations ./docs/integrations
          cp -R /tmp/airbyte_repo/docs/.gitbook ./docs/.gitbook
          [ -f "./docs/integrations/sources/google-ads.md" ] || { ls -Rlha ./docs; echo "::error ::Failed to copy docs from airbyte repository"; exit 21; }

      - name: Build Branch
        uses: ./.github/actions/build-branch
        with:
          branch_version_tag: ${{ needs.generate-tags.outputs.dev_tag }}
          build_docker_images: 'false'

      - name: Publish Dev Jars
        env:
          CLOUDREPO_USER: ${{ secrets.CLOUDREPO_USER }}
          CLOUDREPO_PASSWORD: ${{ secrets.CLOUDREPO_PASSWORD }}
        run: VERSION=${{ needs.generate-tags.outputs.dev_tag }} ./gradlew publish
        shell: bash

      - name: Publish main Jars
        if: needs.generate-tags.outputs.main_tag != ''
        env:
          CLOUDREPO_USER: ${{ secrets.CLOUDREPO_USER }}
          CLOUDREPO_PASSWORD: ${{ secrets.CLOUDREPO_PASSWORD }}
        run: VERSION=${{ needs.generate-tags.outputs.main_tag }} ./gradlew publish
        shell: bash

  docker-push:
    concurrency:
      # only allow one workflow run at a time for a given SHA
      # to prevent multiple runs from pushing artifacts for the same SHA at the same time
      # note: using inputs in the group expression only works when specifying concurrency at the job level
      group: ${{ github.workflow }}-${{ inputs.oss_ref || github.sha }}
      cancel-in-progress: false
    name: "Push Docker Images"
    needs:
      - start-runner
      - generate-tags
      - oss-branch-build
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Login to Docker (on main)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Prepare Docker buildx
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name oss-buildx --driver docker-container --use
        shell: bash

      - name: Set Git Revision
        run: |
          GIT_REVISION=$(git rev-parse HEAD)
          [ [ -z "$GIT_REVISION" ] ] && echo "Couldn't get the git revision..." && exit 1
          echo "GIT_REVISION=${GIT_REVISION}" >> $GITHUB_ENV
        shell: bash

      - name: Prepare Runner for Building
        uses: ./.github/actions/runner-prepare-for-build

        # Put tars/artifacts in the correct build directories so docker buildx can find the artifacts it needs when building docker images
      - name: Prepare Docker context
        run: VERSION=${{ needs.generate-tags.outputs.dev_tag }} ./gradlew copyGeneratedTar airbyte-db:db-lib:copyInitSql
        shell: bash

        # Build docker images using docker buildx (for multi platform)
      - name: Push Docker Images
        env:
          VERSION: ${{ needs.generate-tags.outputs.dev_tag }}
          ALT_TAG: ${{ needs.generate-tags.outputs.main_tag }}
        run: GIT_REVISION=$GIT_REVISION docker buildx bake -f docker-compose-cloud.buildx.yaml --push
        shell: bash

      - name: Cleanup Docker buildx
        run: docker buildx rm oss-buildx
        shell: bash

  stop-runner:
    name: "Stop Build EC2 Runner"
    timeout-minutes: 10
    needs:
      - start-runner # required to get output from the start-runner job
      - docker-push # wait until all publish steps are done
    runs-on: ubuntu-latest
    # Always is required to stop the runner even if the previous job has errors. However always() runs even if the previous step is skipped.
    # Thus, we check for skipped here.
    if: ${{ always() && needs.start-runner.result != 'skipped'}}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Checkout Airbyte
        uses: actions/checkout@v3
      - name: Check PAT rate limits
        run: |
          ./tools/bin/find_non_rate_limited_PAT \
            ${{ secrets.GH_PAT_BUILD_RUNNER_OSS }} \
            ${{ secrets.GH_PAT_BUILD_RUNNER_BACKUP }}
      - name: Stop EC2 runner
        uses: airbytehq/ec2-github-runner@base64v1.1.0
        with:
          mode: stop
          github-token: ${{ env.PAT }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
