import { defineConfig } from "orval";

// Eslint command to run orval generated code with, that ignores our regular eslint config
// but only applies rules from the orval specific eslint config
const eslintOutput = "eslint --fix --no-eslintrc --config .eslintrc.orval.js --no-inline-config";

export default defineConfig({
  api: {
    input: "../airbyte-api/src/main/openapi/config.yaml",
    output: {
      target: "./src/core/request/AirbyteClient.ts",
      prettier: true,
      override: {
        header: (info) => [
          `eslint-disable`,
          `Generated by orval 🍺`,
          `Do not edit manually. Run "npm run generate-client" instead.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        mutator: {
          path: "./src/core/request/apiOverride.ts",
          name: "apiOverride",
        },
      },
    },
    hooks: {
      afterAllFilesWrite: eslintOutput,
    },
  },
  connectorBuilder: {
    input: "../airbyte-connector-builder-server/src/main/openapi/openapi.yaml",
    output: {
      target: "./src/core/request/ConnectorBuilderClient.ts",
      prettier: true,
      override: {
        header: (info) => [
          `eslint-disable`,
          `Generated by orval 🍺`,
          `Do not edit manually. Run "npm run generate-client" instead.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        mutator: {
          path: "./src/core/request/apiOverride.ts",
          name: "apiOverride",
        },
      },
    },
    hooks: {
      afterAllFilesWrite: eslintOutput,
    },
  },
  connectorManifest: {
    input: "./src/services/connectorBuilder/connector_manifest_openapi.yaml",
    output: {
      target: "./src/core/request/ConnectorManifest.ts",
      prettier: true,
      override: {
        header: (info) => [
          `eslint-disable`,
          `Generated by orval 🍺`,
          `Do not edit manually. Run "npm run generate-client" instead.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
  },
});
